package de.uni_koblenz.jgralab.gretl.parser;

public enum TokenTypes {
	TRANSFORMATION, TRANSFORM_ARROW, DEFINES, PAREN_OPEN, PAREN_CLOSE, COLON, SEMICOLON, IDENT, EOF, FROM, TO, ROLE, AGGREGATION, COMMA, GREQL, GREQL_IMPORT, ASSIGN, STRING, DOMAIN_SPECIFIC
}
