language: java
notifications:
  email:
    recipients:
      - re-group@list.uni-koblenz.de
  irc:
    channels:
      - "irc.freenode.org#jgralab"
    use_notice: true
install: ant
script: ant test
jdk:
  - openjdk7
  - openjdk8
  - oraclejdk7
  - oraclejdk8
