dist: xenial
language: java
addons:
  apt:
    packages:
      - ant
jdk:
  - openjdk8
notifications:
  email:
    recipients:
      - re-group@list.uni-koblenz.de
  irc:
    channels:
      - "irc.freenode.org#jgralab"
    use_notice: true
install: ant build
script: ant -lib lib/junit/ant-junit.jar:lib/junit/junit-4.7.jar test
