/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.utilities.tg2schemagraph.grumlschema.impl;

import de.uni_koblenz.jgralab.impl.array.CompositionImpl;

import de.uni_koblenz.jgralab.CompositionClass;
import de.uni_koblenz.jgralab.AttributedElement;
import de.uni_koblenz.jgralab.Composition;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;

import de.uni_koblenz.jgralab.utilities.tg2schemagraph.grumlschema.impl.ReversedContainsGraphElementClassM2Impl;

import de.uni_koblenz.jgralab.utilities.tg2schemagraph.grumlschema.ContainsGraphElementClassM2;

import java.io.IOException;
/**
FromVertexClass: GraphElementClassM2
FromRoleName : 
ToVertexClass: GraphClassM2
toRoleName : 
 */

public class ContainsGraphElementClassM2Impl extends CompositionImpl implements Composition, ContainsGraphElementClassM2 {

	public ContainsGraphElementClassM2Impl(int id, Graph g) {
		super(id, g, (CompositionClass)g.getGraphClass().getGraphElementClass("ContainsGraphElementClassM2"));
		reversedEdge = new ReversedContainsGraphElementClassM2Impl(this, g);
	}

	public Class<? extends AttributedElement> getM1Class() {
		return ContainsGraphElementClassM2.class;
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		throw new NoSuchFieldException("ContainsGraphElementClassM2 doesn't contain an attribute " + attributeName);
	}

	@SuppressWarnings("unchecked")
	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		throw new NoSuchFieldException("ContainsGraphElementClassM2 doesn't contain an attribute " + attributeName);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public ContainsGraphElementClassM2 getNextContainsGraphElementClassM2InGraph() {
		return (ContainsGraphElementClassM2)getNextEdgeOfClassInGraph(ContainsGraphElementClassM2.class);
	}

	public ContainsGraphElementClassM2 getNextContainsGraphElementClassM2InGraph(boolean noSubClasses) {
		return (ContainsGraphElementClassM2)getNextEdgeOfClassInGraph(ContainsGraphElementClassM2.class, noSubClasses);
	}

	public ContainsGraphElementClassM2 getNextContainsGraphElementClassM2() {
		return (ContainsGraphElementClassM2)getNextEdgeOfClass(ContainsGraphElementClassM2.class);
	}

	public ContainsGraphElementClassM2 getNextContainsGraphElementClassM2(EdgeDirection orientation) {
		return (ContainsGraphElementClassM2)getNextEdgeOfClass(ContainsGraphElementClassM2.class, orientation);
	}

	public ContainsGraphElementClassM2 getNextContainsGraphElementClassM2(boolean noSubClasses) {
		return (ContainsGraphElementClassM2)getNextEdgeOfClass(ContainsGraphElementClassM2.class, noSubClasses);
	}

	public ContainsGraphElementClassM2 getNextContainsGraphElementClassM2(EdgeDirection orientation, boolean noSubClasses) {
		return (ContainsGraphElementClassM2)getNextEdgeOfClass(ContainsGraphElementClassM2.class, orientation, noSubClasses);
	}

}
