/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.utilities.tg2schemagraph.grumlschema.impl;

import de.uni_koblenz.jgralab.impl.array.AggregationImpl;

import de.uni_koblenz.jgralab.AggregationClass;
import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.AttributedElement;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;

import de.uni_koblenz.jgralab.utilities.tg2schemagraph.grumlschema.impl.ReversedHasAttributeM2Impl;

import de.uni_koblenz.jgralab.utilities.tg2schemagraph.grumlschema.HasAttributeM2;

import java.io.IOException;
/**
FromVertexClass: AttributeM2
FromRoleName : 
ToVertexClass: AttributedElementClassM2
toRoleName : 
 */

public class HasAttributeM2Impl extends AggregationImpl implements Aggregation, HasAttributeM2 {

	public HasAttributeM2Impl(int id, Graph g) {
		super(id, g, (AggregationClass)g.getGraphClass().getGraphElementClass("HasAttributeM2"));
		reversedEdge = new ReversedHasAttributeM2Impl(this, g);
	}

	public Class<? extends AttributedElement> getM1Class() {
		return HasAttributeM2.class;
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		throw new NoSuchFieldException("HasAttributeM2 doesn't contain an attribute " + attributeName);
	}

	@SuppressWarnings("unchecked")
	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		throw new NoSuchFieldException("HasAttributeM2 doesn't contain an attribute " + attributeName);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public HasAttributeM2 getNextHasAttributeM2InGraph() {
		return (HasAttributeM2)getNextEdgeOfClassInGraph(HasAttributeM2.class);
	}

	public HasAttributeM2 getNextHasAttributeM2InGraph(boolean noSubClasses) {
		return (HasAttributeM2)getNextEdgeOfClassInGraph(HasAttributeM2.class, noSubClasses);
	}

	public HasAttributeM2 getNextHasAttributeM2() {
		return (HasAttributeM2)getNextEdgeOfClass(HasAttributeM2.class);
	}

	public HasAttributeM2 getNextHasAttributeM2(EdgeDirection orientation) {
		return (HasAttributeM2)getNextEdgeOfClass(HasAttributeM2.class, orientation);
	}

	public HasAttributeM2 getNextHasAttributeM2(boolean noSubClasses) {
		return (HasAttributeM2)getNextEdgeOfClass(HasAttributeM2.class, noSubClasses);
	}

	public HasAttributeM2 getNextHasAttributeM2(EdgeDirection orientation, boolean noSubClasses) {
		return (HasAttributeM2)getNextEdgeOfClass(HasAttributeM2.class, orientation, noSubClasses);
	}

}
