/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.utilities.tg2schemagraph.grumlschema.impl;

import de.uni_koblenz.jgralab.impl.array.ReversedAggregationImpl;
import de.uni_koblenz.jgralab.impl.array.EdgeImpl;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;

import de.uni_koblenz.jgralab.utilities.tg2schemagraph.grumlschema.HasRecordDomainComponentM2;

import java.io.IOException;

public class ReversedHasRecordDomainComponentM2Impl extends ReversedAggregationImpl implements Aggregation, HasRecordDomainComponentM2 {

	ReversedHasRecordDomainComponentM2Impl(EdgeImpl e, Graph g) {
		super(e, g);
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		return ((HasRecordDomainComponentM2)normalEdge).getAttribute(attributeName);
	}

	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		((HasRecordDomainComponentM2)normalEdge).setAttribute(attributeName, data);
	}

	public String getName() {
		return ((HasRecordDomainComponentM2)normalEdge).getName();
	}

	public void setName(String name) {
		((HasRecordDomainComponentM2)normalEdge).setName(name);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public HasRecordDomainComponentM2 getNextHasRecordDomainComponentM2InGraph() {
		return ((HasRecordDomainComponentM2)normalEdge).getNextHasRecordDomainComponentM2InGraph();
	}

	public HasRecordDomainComponentM2 getNextHasRecordDomainComponentM2InGraph(boolean noSubClasses) {
		return ((HasRecordDomainComponentM2)normalEdge).getNextHasRecordDomainComponentM2InGraph(noSubClasses);
	}

	public HasRecordDomainComponentM2 getNextHasRecordDomainComponentM2() {
		return (HasRecordDomainComponentM2)getNextEdgeOfClass(HasRecordDomainComponentM2.class);
	}

	public HasRecordDomainComponentM2 getNextHasRecordDomainComponentM2(EdgeDirection orientation) {
		return (HasRecordDomainComponentM2)getNextEdgeOfClass(HasRecordDomainComponentM2.class, orientation);
	}

	public HasRecordDomainComponentM2 getNextHasRecordDomainComponentM2(boolean noSubClasses) {
		return (HasRecordDomainComponentM2)getNextEdgeOfClass(HasRecordDomainComponentM2.class, noSubClasses);
	}

	public HasRecordDomainComponentM2 getNextHasRecordDomainComponentM2(EdgeDirection orientation, boolean noSubClasses) {
		return (HasRecordDomainComponentM2)getNextEdgeOfClass(HasRecordDomainComponentM2.class, orientation, noSubClasses);
	}

}
