/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.utilities.tg2schemagraph.grumlschema.impl;

import de.uni_koblenz.jgralab.impl.array.ReversedCompositionImpl;
import de.uni_koblenz.jgralab.impl.array.EdgeImpl;

import de.uni_koblenz.jgralab.Composition;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;

import de.uni_koblenz.jgralab.utilities.tg2schemagraph.grumlschema.ContainsGraphElementClassM2;

import java.io.IOException;

public class ReversedContainsGraphElementClassM2Impl extends ReversedCompositionImpl implements Composition, ContainsGraphElementClassM2 {

	ReversedContainsGraphElementClassM2Impl(EdgeImpl e, Graph g) {
		super(e, g);
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		return ((ContainsGraphElementClassM2)normalEdge).getAttribute(attributeName);
	}

	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		((ContainsGraphElementClassM2)normalEdge).setAttribute(attributeName, data);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public ContainsGraphElementClassM2 getNextContainsGraphElementClassM2InGraph() {
		return ((ContainsGraphElementClassM2)normalEdge).getNextContainsGraphElementClassM2InGraph();
	}

	public ContainsGraphElementClassM2 getNextContainsGraphElementClassM2InGraph(boolean noSubClasses) {
		return ((ContainsGraphElementClassM2)normalEdge).getNextContainsGraphElementClassM2InGraph(noSubClasses);
	}

	public ContainsGraphElementClassM2 getNextContainsGraphElementClassM2() {
		return (ContainsGraphElementClassM2)getNextEdgeOfClass(ContainsGraphElementClassM2.class);
	}

	public ContainsGraphElementClassM2 getNextContainsGraphElementClassM2(EdgeDirection orientation) {
		return (ContainsGraphElementClassM2)getNextEdgeOfClass(ContainsGraphElementClassM2.class, orientation);
	}

	public ContainsGraphElementClassM2 getNextContainsGraphElementClassM2(boolean noSubClasses) {
		return (ContainsGraphElementClassM2)getNextEdgeOfClass(ContainsGraphElementClassM2.class, noSubClasses);
	}

	public ContainsGraphElementClassM2 getNextContainsGraphElementClassM2(EdgeDirection orientation, boolean noSubClasses) {
		return (ContainsGraphElementClassM2)getNextEdgeOfClass(ContainsGraphElementClassM2.class, orientation, noSubClasses);
	}

}
