/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.utilities.tg2schemagraph.grumlschema;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;

import de.uni_koblenz.jgralab.utilities.tg2schemagraph.grumlschema.impl.HasRecordDomainComponentM2Impl;
/**
FromVertexClass: RecordDomainM2
FromRoleName : 
ToVertexClass: DomainM2
toRoleName : 
 */

public interface HasRecordDomainComponentM2 extends Aggregation {

	/**
	 * refers to the default implementation class of this interface
	 */
	public static final Class<HasRecordDomainComponentM2Impl> IMPLEMENTATION_CLASS = HasRecordDomainComponentM2Impl.class;

	public String getName();

	public void setName(String name);

	/**
	 * @return the next HasRecordDomainComponentM2 edge in the global edge sequence
	 */
	public HasRecordDomainComponentM2 getNextHasRecordDomainComponentM2InGraph();

	/**
	 * @return the next HasRecordDomainComponentM2 edge in the global edge sequence
	 * @param noSubClasses if set to <code>true</code>, no subclasses of HasRecordDomainComponentM2 are accepted
	 */
	public HasRecordDomainComponentM2 getNextHasRecordDomainComponentM2InGraph(boolean noSubClasses);

	/**
	 * @return the next edge of class HasRecordDomainComponentM2 at the "this" vertex
	 */
	public HasRecordDomainComponentM2 getNextHasRecordDomainComponentM2();

	/**
	 * @return the next edge of class HasRecordDomainComponentM2 at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public HasRecordDomainComponentM2 getNextHasRecordDomainComponentM2(EdgeDirection orientation);

	/**
	 * @return the next edge of class HasRecordDomainComponentM2 at the "this" vertex
	 * @param noSubClasses if set to <code>true</code>, no subclasses of HasRecordDomainComponentM2 are accepted
	 */
	public HasRecordDomainComponentM2 getNextHasRecordDomainComponentM2(boolean noSubClasses);

	/**
	 * @return the next edge of class HasRecordDomainComponentM2 at the "this" vertex
	 * @param orientation the orientation of the edge
	 * @param noSubClasses if set to <code>true</code>, no subclasses of HasRecordDomainComponentM2 are accepted
	 */
	public HasRecordDomainComponentM2 getNextHasRecordDomainComponentM2(EdgeDirection orientation, boolean noSubClasses);

}
