/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema.impl;

import de.uni_koblenz.jgralab.impl.array.VertexImpl;
import de.uni_koblenz.jgralab.impl.IncidenceIterable;

import de.uni_koblenz.jgralab.VertexClass;
import de.uni_koblenz.jgralab.AttributedElement;
import de.uni_koblenz.jgralab.Edge;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.EdgeVertexPair;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;
import de.uni_koblenz.jgralab.Vertex;

import de.uni_koblenz.jgralab.greql2.schema.EdgeRestriction;
import de.uni_koblenz.jgralab.greql2.schema.Greql2Aggregation;
import de.uni_koblenz.jgralab.greql2.schema.Greql2Vertex;
import de.uni_koblenz.jgralab.greql2.schema.IsBoundExprOf;
import de.uni_koblenz.jgralab.greql2.schema.IsEdgeRestrOf;
import de.uni_koblenz.jgralab.greql2.schema.IsRoleIdOf;
import de.uni_koblenz.jgralab.greql2.schema.IsTypeExprOf;
import de.uni_koblenz.jgralab.greql2.schema.IsTypeIdOf;

import java.io.IOException;
import java.util.HashSet;
import java.util.Set;

public class EdgeRestrictionImpl extends VertexImpl implements EdgeRestriction, Greql2Vertex, Vertex {

	public EdgeRestrictionImpl(int id, Graph g) {
		super(id, g, (VertexClass)g.getGraphClass().getGraphElementClass("EdgeRestriction"));
	}

	public Class<? extends AttributedElement> getM1Class() {
		return EdgeRestriction.class;
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		throw new NoSuchFieldException("EdgeRestriction doesn't contain an attribute " + attributeName);
	}

	@SuppressWarnings("unchecked")
	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		throw new NoSuchFieldException("EdgeRestriction doesn't contain an attribute " + attributeName);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	/* add all valid from edges */
	private static Set<Class<? extends Edge>> validFromEdges = new HashSet<Class<? extends Edge>>();
	
	/* (non-Javadoc)
	 * @see jgralab.Vertex:isValidAlpha()
	 */
	public boolean isValidAlpha(Edge edge) {
		return validFromEdges.contains(edge.getClass());
	}
	
	{

		validFromEdges.add(IsEdgeRestrOfImpl.class);

	}
	
	/* add all valid to edges */
	private static Set<Class<? extends Edge>> validToEdges = new HashSet<Class<? extends Edge>>();
	
	/* (non-Javadoc)
	 * @see jgralab.Vertex:isValidOemga()
	 */
	public boolean isValidOmega(Edge edge) {
		return validToEdges.contains(edge.getClass());
	}
	
	{

		validToEdges.add(IsRoleIdOfImpl.class);

		validToEdges.add(IsTypeIdOfImpl.class);

	}

	public EdgeRestriction getNextEdgeRestriction() {
		return (EdgeRestriction)getNextVertexOfClass(EdgeRestriction.class);
	}

	public EdgeRestriction getNextEdgeRestriction(boolean noSubClasses) {
		return (EdgeRestriction)getNextVertexOfClass(EdgeRestriction.class, noSubClasses);
	}

	public Greql2Vertex getNextGreql2Vertex() {
		return (Greql2Vertex)getNextVertexOfClass(Greql2Vertex.class);
	}

	public IsRoleIdOf getFirstIsRoleIdOf() {
		return (IsRoleIdOf)getFirstEdgeOfClass(IsRoleIdOf.class);
	}

	public IsRoleIdOf getFirstIsRoleIdOf(EdgeDirection orientation) {
		return (IsRoleIdOf)getFirstEdgeOfClass(IsRoleIdOf.class, orientation);
	}

	public IsRoleIdOf getFirstIsRoleIdOf(boolean noSubClasses) {
		return (IsRoleIdOf)getFirstEdgeOfClass(IsRoleIdOf.class, noSubClasses);
	}

	public IsRoleIdOf getFirstIsRoleIdOf(EdgeDirection orientation, boolean noSubClasses) {
		return (IsRoleIdOf)getFirstEdgeOfClass(IsRoleIdOf.class, orientation, noSubClasses);
	}

	public IsBoundExprOf getFirstIsBoundExprOf() {
		return (IsBoundExprOf)getFirstEdgeOfClass(IsBoundExprOf.class);
	}

	public IsBoundExprOf getFirstIsBoundExprOf(EdgeDirection orientation) {
		return (IsBoundExprOf)getFirstEdgeOfClass(IsBoundExprOf.class, orientation);
	}

	public Greql2Aggregation getFirstGreql2Aggregation() {
		return (Greql2Aggregation)getFirstEdgeOfClass(Greql2Aggregation.class);
	}

	public Greql2Aggregation getFirstGreql2Aggregation(EdgeDirection orientation) {
		return (Greql2Aggregation)getFirstEdgeOfClass(Greql2Aggregation.class, orientation);
	}

	public IsTypeExprOf getFirstIsTypeExprOf() {
		return (IsTypeExprOf)getFirstEdgeOfClass(IsTypeExprOf.class);
	}

	public IsTypeExprOf getFirstIsTypeExprOf(EdgeDirection orientation) {
		return (IsTypeExprOf)getFirstEdgeOfClass(IsTypeExprOf.class, orientation);
	}

	public IsEdgeRestrOf getFirstIsEdgeRestrOf() {
		return (IsEdgeRestrOf)getFirstEdgeOfClass(IsEdgeRestrOf.class);
	}

	public IsEdgeRestrOf getFirstIsEdgeRestrOf(EdgeDirection orientation) {
		return (IsEdgeRestrOf)getFirstEdgeOfClass(IsEdgeRestrOf.class, orientation);
	}

	public IsEdgeRestrOf getFirstIsEdgeRestrOf(boolean noSubClasses) {
		return (IsEdgeRestrOf)getFirstEdgeOfClass(IsEdgeRestrOf.class, noSubClasses);
	}

	public IsEdgeRestrOf getFirstIsEdgeRestrOf(EdgeDirection orientation, boolean noSubClasses) {
		return (IsEdgeRestrOf)getFirstEdgeOfClass(IsEdgeRestrOf.class, orientation, noSubClasses);
	}

	public IsTypeIdOf getFirstIsTypeIdOf() {
		return (IsTypeIdOf)getFirstEdgeOfClass(IsTypeIdOf.class);
	}

	public IsTypeIdOf getFirstIsTypeIdOf(EdgeDirection orientation) {
		return (IsTypeIdOf)getFirstEdgeOfClass(IsTypeIdOf.class, orientation);
	}

	public IsTypeIdOf getFirstIsTypeIdOf(boolean noSubClasses) {
		return (IsTypeIdOf)getFirstEdgeOfClass(IsTypeIdOf.class, noSubClasses);
	}

	public IsTypeIdOf getFirstIsTypeIdOf(EdgeDirection orientation, boolean noSubClasses) {
		return (IsTypeIdOf)getFirstEdgeOfClass(IsTypeIdOf.class, orientation, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends IsRoleIdOf, ? extends Vertex>> getIsRoleIdOfIncidences() {
		return new IncidenceIterable<IsRoleIdOf, Vertex>(this, IsRoleIdOf.class);
	}
	
	public Iterable<EdgeVertexPair<? extends IsRoleIdOf, ? extends Vertex>> getIsRoleIdOfIncidences(boolean noSubClasses) {
		return new IncidenceIterable<IsRoleIdOf, Vertex>(this, IsRoleIdOf.class, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends IsRoleIdOf, ? extends Vertex>> getIsRoleIdOfIncidences(EdgeDirection direction, boolean noSubClasses) {
		return  new IncidenceIterable<IsRoleIdOf, Vertex>(this, IsRoleIdOf.class, direction, noSubClasses);
	}
	
	public Iterable<EdgeVertexPair<? extends IsRoleIdOf, ? extends Vertex>> getIsRoleIdOfIncidences(EdgeDirection direction) {
		return new IncidenceIterable<IsRoleIdOf, Vertex>(this, IsRoleIdOf.class, direction);
	}

	public Iterable<EdgeVertexPair<? extends IsBoundExprOf, ? extends Vertex>> getIsBoundExprOfIncidences() {
		return new IncidenceIterable<IsBoundExprOf, Vertex>(this, IsBoundExprOf.class);
	}
	
	public Iterable<EdgeVertexPair<? extends IsBoundExprOf, ? extends Vertex>> getIsBoundExprOfIncidences(boolean noSubClasses) {
		return new IncidenceIterable<IsBoundExprOf, Vertex>(this, IsBoundExprOf.class, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends IsBoundExprOf, ? extends Vertex>> getIsBoundExprOfIncidences(EdgeDirection direction, boolean noSubClasses) {
		return  new IncidenceIterable<IsBoundExprOf, Vertex>(this, IsBoundExprOf.class, direction, noSubClasses);
	}
	
	public Iterable<EdgeVertexPair<? extends IsBoundExprOf, ? extends Vertex>> getIsBoundExprOfIncidences(EdgeDirection direction) {
		return new IncidenceIterable<IsBoundExprOf, Vertex>(this, IsBoundExprOf.class, direction);
	}

	public Iterable<EdgeVertexPair<? extends Greql2Aggregation, ? extends Vertex>> getGreql2AggregationIncidences() {
		return new IncidenceIterable<Greql2Aggregation, Vertex>(this, Greql2Aggregation.class);
	}
	
	public Iterable<EdgeVertexPair<? extends Greql2Aggregation, ? extends Vertex>> getGreql2AggregationIncidences(boolean noSubClasses) {
		return new IncidenceIterable<Greql2Aggregation, Vertex>(this, Greql2Aggregation.class, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends Greql2Aggregation, ? extends Vertex>> getGreql2AggregationIncidences(EdgeDirection direction, boolean noSubClasses) {
		return  new IncidenceIterable<Greql2Aggregation, Vertex>(this, Greql2Aggregation.class, direction, noSubClasses);
	}
	
	public Iterable<EdgeVertexPair<? extends Greql2Aggregation, ? extends Vertex>> getGreql2AggregationIncidences(EdgeDirection direction) {
		return new IncidenceIterable<Greql2Aggregation, Vertex>(this, Greql2Aggregation.class, direction);
	}

	public Iterable<EdgeVertexPair<? extends IsTypeExprOf, ? extends Vertex>> getIsTypeExprOfIncidences() {
		return new IncidenceIterable<IsTypeExprOf, Vertex>(this, IsTypeExprOf.class);
	}
	
	public Iterable<EdgeVertexPair<? extends IsTypeExprOf, ? extends Vertex>> getIsTypeExprOfIncidences(boolean noSubClasses) {
		return new IncidenceIterable<IsTypeExprOf, Vertex>(this, IsTypeExprOf.class, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends IsTypeExprOf, ? extends Vertex>> getIsTypeExprOfIncidences(EdgeDirection direction, boolean noSubClasses) {
		return  new IncidenceIterable<IsTypeExprOf, Vertex>(this, IsTypeExprOf.class, direction, noSubClasses);
	}
	
	public Iterable<EdgeVertexPair<? extends IsTypeExprOf, ? extends Vertex>> getIsTypeExprOfIncidences(EdgeDirection direction) {
		return new IncidenceIterable<IsTypeExprOf, Vertex>(this, IsTypeExprOf.class, direction);
	}

	public Iterable<EdgeVertexPair<? extends IsEdgeRestrOf, ? extends Vertex>> getIsEdgeRestrOfIncidences() {
		return new IncidenceIterable<IsEdgeRestrOf, Vertex>(this, IsEdgeRestrOf.class);
	}
	
	public Iterable<EdgeVertexPair<? extends IsEdgeRestrOf, ? extends Vertex>> getIsEdgeRestrOfIncidences(boolean noSubClasses) {
		return new IncidenceIterable<IsEdgeRestrOf, Vertex>(this, IsEdgeRestrOf.class, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends IsEdgeRestrOf, ? extends Vertex>> getIsEdgeRestrOfIncidences(EdgeDirection direction, boolean noSubClasses) {
		return  new IncidenceIterable<IsEdgeRestrOf, Vertex>(this, IsEdgeRestrOf.class, direction, noSubClasses);
	}
	
	public Iterable<EdgeVertexPair<? extends IsEdgeRestrOf, ? extends Vertex>> getIsEdgeRestrOfIncidences(EdgeDirection direction) {
		return new IncidenceIterable<IsEdgeRestrOf, Vertex>(this, IsEdgeRestrOf.class, direction);
	}

	public Iterable<EdgeVertexPair<? extends IsTypeIdOf, ? extends Vertex>> getIsTypeIdOfIncidences() {
		return new IncidenceIterable<IsTypeIdOf, Vertex>(this, IsTypeIdOf.class);
	}
	
	public Iterable<EdgeVertexPair<? extends IsTypeIdOf, ? extends Vertex>> getIsTypeIdOfIncidences(boolean noSubClasses) {
		return new IncidenceIterable<IsTypeIdOf, Vertex>(this, IsTypeIdOf.class, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends IsTypeIdOf, ? extends Vertex>> getIsTypeIdOfIncidences(EdgeDirection direction, boolean noSubClasses) {
		return  new IncidenceIterable<IsTypeIdOf, Vertex>(this, IsTypeIdOf.class, direction, noSubClasses);
	}
	
	public Iterable<EdgeVertexPair<? extends IsTypeIdOf, ? extends Vertex>> getIsTypeIdOfIncidences(EdgeDirection direction) {
		return new IncidenceIterable<IsTypeIdOf, Vertex>(this, IsTypeIdOf.class, direction);
	}

}
