/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema.impl;

import de.uni_koblenz.jgralab.impl.array.VertexImpl;
import de.uni_koblenz.jgralab.impl.IncidenceIterable;

import de.uni_koblenz.jgralab.VertexClass;
import de.uni_koblenz.jgralab.AttributedElement;
import de.uni_koblenz.jgralab.Edge;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.EdgeVertexPair;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;
import de.uni_koblenz.jgralab.Vertex;

import de.uni_koblenz.jgralab.greql2.schema.Greql2Aggregation;
import de.uni_koblenz.jgralab.greql2.schema.Greql2Vertex;
import de.uni_koblenz.jgralab.greql2.schema.IsBoundExprOf;
import de.uni_koblenz.jgralab.greql2.schema.IsRecordElementOf;
import de.uni_koblenz.jgralab.greql2.schema.IsRecordExprOf;
import de.uni_koblenz.jgralab.greql2.schema.IsRecordIdOf;
import de.uni_koblenz.jgralab.greql2.schema.IsTypeExprOf;
import de.uni_koblenz.jgralab.greql2.schema.RecordElement;

import java.io.IOException;
import java.util.HashSet;
import java.util.Set;

public class RecordElementImpl extends VertexImpl implements Greql2Vertex, RecordElement, Vertex {

	public RecordElementImpl(int id, Graph g) {
		super(id, g, (VertexClass)g.getGraphClass().getGraphElementClass("RecordElement"));
	}

	public Class<? extends AttributedElement> getM1Class() {
		return RecordElement.class;
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		throw new NoSuchFieldException("RecordElement doesn't contain an attribute " + attributeName);
	}

	@SuppressWarnings("unchecked")
	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		throw new NoSuchFieldException("RecordElement doesn't contain an attribute " + attributeName);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	/* add all valid from edges */
	private static Set<Class<? extends Edge>> validFromEdges = new HashSet<Class<? extends Edge>>();
	
	/* (non-Javadoc)
	 * @see jgralab.Vertex:isValidAlpha()
	 */
	public boolean isValidAlpha(Edge edge) {
		return validFromEdges.contains(edge.getClass());
	}
	
	{

		validFromEdges.add(IsRecordElementOfImpl.class);

	}
	
	/* add all valid to edges */
	private static Set<Class<? extends Edge>> validToEdges = new HashSet<Class<? extends Edge>>();
	
	/* (non-Javadoc)
	 * @see jgralab.Vertex:isValidOemga()
	 */
	public boolean isValidOmega(Edge edge) {
		return validToEdges.contains(edge.getClass());
	}
	
	{

		validToEdges.add(IsRecordExprOfImpl.class);

		validToEdges.add(IsRecordIdOfImpl.class);

	}

	public Greql2Vertex getNextGreql2Vertex() {
		return (Greql2Vertex)getNextVertexOfClass(Greql2Vertex.class);
	}

	public RecordElement getNextRecordElement() {
		return (RecordElement)getNextVertexOfClass(RecordElement.class);
	}

	public RecordElement getNextRecordElement(boolean noSubClasses) {
		return (RecordElement)getNextVertexOfClass(RecordElement.class, noSubClasses);
	}

	public IsBoundExprOf getFirstIsBoundExprOf() {
		return (IsBoundExprOf)getFirstEdgeOfClass(IsBoundExprOf.class);
	}

	public IsBoundExprOf getFirstIsBoundExprOf(EdgeDirection orientation) {
		return (IsBoundExprOf)getFirstEdgeOfClass(IsBoundExprOf.class, orientation);
	}

	public IsRecordExprOf getFirstIsRecordExprOf() {
		return (IsRecordExprOf)getFirstEdgeOfClass(IsRecordExprOf.class);
	}

	public IsRecordExprOf getFirstIsRecordExprOf(EdgeDirection orientation) {
		return (IsRecordExprOf)getFirstEdgeOfClass(IsRecordExprOf.class, orientation);
	}

	public IsRecordExprOf getFirstIsRecordExprOf(boolean noSubClasses) {
		return (IsRecordExprOf)getFirstEdgeOfClass(IsRecordExprOf.class, noSubClasses);
	}

	public IsRecordExprOf getFirstIsRecordExprOf(EdgeDirection orientation, boolean noSubClasses) {
		return (IsRecordExprOf)getFirstEdgeOfClass(IsRecordExprOf.class, orientation, noSubClasses);
	}

	public Greql2Aggregation getFirstGreql2Aggregation() {
		return (Greql2Aggregation)getFirstEdgeOfClass(Greql2Aggregation.class);
	}

	public Greql2Aggregation getFirstGreql2Aggregation(EdgeDirection orientation) {
		return (Greql2Aggregation)getFirstEdgeOfClass(Greql2Aggregation.class, orientation);
	}

	public IsTypeExprOf getFirstIsTypeExprOf() {
		return (IsTypeExprOf)getFirstEdgeOfClass(IsTypeExprOf.class);
	}

	public IsTypeExprOf getFirstIsTypeExprOf(EdgeDirection orientation) {
		return (IsTypeExprOf)getFirstEdgeOfClass(IsTypeExprOf.class, orientation);
	}

	public IsRecordElementOf getFirstIsRecordElementOf() {
		return (IsRecordElementOf)getFirstEdgeOfClass(IsRecordElementOf.class);
	}

	public IsRecordElementOf getFirstIsRecordElementOf(EdgeDirection orientation) {
		return (IsRecordElementOf)getFirstEdgeOfClass(IsRecordElementOf.class, orientation);
	}

	public IsRecordElementOf getFirstIsRecordElementOf(boolean noSubClasses) {
		return (IsRecordElementOf)getFirstEdgeOfClass(IsRecordElementOf.class, noSubClasses);
	}

	public IsRecordElementOf getFirstIsRecordElementOf(EdgeDirection orientation, boolean noSubClasses) {
		return (IsRecordElementOf)getFirstEdgeOfClass(IsRecordElementOf.class, orientation, noSubClasses);
	}

	public IsRecordIdOf getFirstIsRecordIdOf() {
		return (IsRecordIdOf)getFirstEdgeOfClass(IsRecordIdOf.class);
	}

	public IsRecordIdOf getFirstIsRecordIdOf(EdgeDirection orientation) {
		return (IsRecordIdOf)getFirstEdgeOfClass(IsRecordIdOf.class, orientation);
	}

	public IsRecordIdOf getFirstIsRecordIdOf(boolean noSubClasses) {
		return (IsRecordIdOf)getFirstEdgeOfClass(IsRecordIdOf.class, noSubClasses);
	}

	public IsRecordIdOf getFirstIsRecordIdOf(EdgeDirection orientation, boolean noSubClasses) {
		return (IsRecordIdOf)getFirstEdgeOfClass(IsRecordIdOf.class, orientation, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends IsBoundExprOf, ? extends Vertex>> getIsBoundExprOfIncidences() {
		return new IncidenceIterable<IsBoundExprOf, Vertex>(this, IsBoundExprOf.class);
	}
	
	public Iterable<EdgeVertexPair<? extends IsBoundExprOf, ? extends Vertex>> getIsBoundExprOfIncidences(boolean noSubClasses) {
		return new IncidenceIterable<IsBoundExprOf, Vertex>(this, IsBoundExprOf.class, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends IsBoundExprOf, ? extends Vertex>> getIsBoundExprOfIncidences(EdgeDirection direction, boolean noSubClasses) {
		return  new IncidenceIterable<IsBoundExprOf, Vertex>(this, IsBoundExprOf.class, direction, noSubClasses);
	}
	
	public Iterable<EdgeVertexPair<? extends IsBoundExprOf, ? extends Vertex>> getIsBoundExprOfIncidences(EdgeDirection direction) {
		return new IncidenceIterable<IsBoundExprOf, Vertex>(this, IsBoundExprOf.class, direction);
	}

	public Iterable<EdgeVertexPair<? extends IsRecordExprOf, ? extends Vertex>> getIsRecordExprOfIncidences() {
		return new IncidenceIterable<IsRecordExprOf, Vertex>(this, IsRecordExprOf.class);
	}
	
	public Iterable<EdgeVertexPair<? extends IsRecordExprOf, ? extends Vertex>> getIsRecordExprOfIncidences(boolean noSubClasses) {
		return new IncidenceIterable<IsRecordExprOf, Vertex>(this, IsRecordExprOf.class, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends IsRecordExprOf, ? extends Vertex>> getIsRecordExprOfIncidences(EdgeDirection direction, boolean noSubClasses) {
		return  new IncidenceIterable<IsRecordExprOf, Vertex>(this, IsRecordExprOf.class, direction, noSubClasses);
	}
	
	public Iterable<EdgeVertexPair<? extends IsRecordExprOf, ? extends Vertex>> getIsRecordExprOfIncidences(EdgeDirection direction) {
		return new IncidenceIterable<IsRecordExprOf, Vertex>(this, IsRecordExprOf.class, direction);
	}

	public Iterable<EdgeVertexPair<? extends Greql2Aggregation, ? extends Vertex>> getGreql2AggregationIncidences() {
		return new IncidenceIterable<Greql2Aggregation, Vertex>(this, Greql2Aggregation.class);
	}
	
	public Iterable<EdgeVertexPair<? extends Greql2Aggregation, ? extends Vertex>> getGreql2AggregationIncidences(boolean noSubClasses) {
		return new IncidenceIterable<Greql2Aggregation, Vertex>(this, Greql2Aggregation.class, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends Greql2Aggregation, ? extends Vertex>> getGreql2AggregationIncidences(EdgeDirection direction, boolean noSubClasses) {
		return  new IncidenceIterable<Greql2Aggregation, Vertex>(this, Greql2Aggregation.class, direction, noSubClasses);
	}
	
	public Iterable<EdgeVertexPair<? extends Greql2Aggregation, ? extends Vertex>> getGreql2AggregationIncidences(EdgeDirection direction) {
		return new IncidenceIterable<Greql2Aggregation, Vertex>(this, Greql2Aggregation.class, direction);
	}

	public Iterable<EdgeVertexPair<? extends IsTypeExprOf, ? extends Vertex>> getIsTypeExprOfIncidences() {
		return new IncidenceIterable<IsTypeExprOf, Vertex>(this, IsTypeExprOf.class);
	}
	
	public Iterable<EdgeVertexPair<? extends IsTypeExprOf, ? extends Vertex>> getIsTypeExprOfIncidences(boolean noSubClasses) {
		return new IncidenceIterable<IsTypeExprOf, Vertex>(this, IsTypeExprOf.class, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends IsTypeExprOf, ? extends Vertex>> getIsTypeExprOfIncidences(EdgeDirection direction, boolean noSubClasses) {
		return  new IncidenceIterable<IsTypeExprOf, Vertex>(this, IsTypeExprOf.class, direction, noSubClasses);
	}
	
	public Iterable<EdgeVertexPair<? extends IsTypeExprOf, ? extends Vertex>> getIsTypeExprOfIncidences(EdgeDirection direction) {
		return new IncidenceIterable<IsTypeExprOf, Vertex>(this, IsTypeExprOf.class, direction);
	}

	public Iterable<EdgeVertexPair<? extends IsRecordElementOf, ? extends Vertex>> getIsRecordElementOfIncidences() {
		return new IncidenceIterable<IsRecordElementOf, Vertex>(this, IsRecordElementOf.class);
	}
	
	public Iterable<EdgeVertexPair<? extends IsRecordElementOf, ? extends Vertex>> getIsRecordElementOfIncidences(boolean noSubClasses) {
		return new IncidenceIterable<IsRecordElementOf, Vertex>(this, IsRecordElementOf.class, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends IsRecordElementOf, ? extends Vertex>> getIsRecordElementOfIncidences(EdgeDirection direction, boolean noSubClasses) {
		return  new IncidenceIterable<IsRecordElementOf, Vertex>(this, IsRecordElementOf.class, direction, noSubClasses);
	}
	
	public Iterable<EdgeVertexPair<? extends IsRecordElementOf, ? extends Vertex>> getIsRecordElementOfIncidences(EdgeDirection direction) {
		return new IncidenceIterable<IsRecordElementOf, Vertex>(this, IsRecordElementOf.class, direction);
	}

	public Iterable<EdgeVertexPair<? extends IsRecordIdOf, ? extends Vertex>> getIsRecordIdOfIncidences() {
		return new IncidenceIterable<IsRecordIdOf, Vertex>(this, IsRecordIdOf.class);
	}
	
	public Iterable<EdgeVertexPair<? extends IsRecordIdOf, ? extends Vertex>> getIsRecordIdOfIncidences(boolean noSubClasses) {
		return new IncidenceIterable<IsRecordIdOf, Vertex>(this, IsRecordIdOf.class, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends IsRecordIdOf, ? extends Vertex>> getIsRecordIdOfIncidences(EdgeDirection direction, boolean noSubClasses) {
		return  new IncidenceIterable<IsRecordIdOf, Vertex>(this, IsRecordIdOf.class, direction, noSubClasses);
	}
	
	public Iterable<EdgeVertexPair<? extends IsRecordIdOf, ? extends Vertex>> getIsRecordIdOfIncidences(EdgeDirection direction) {
		return new IncidenceIterable<IsRecordIdOf, Vertex>(this, IsRecordIdOf.class, direction);
	}

}
