/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema.impl;

import de.uni_koblenz.jgralab.impl.array.ReversedAggregationImpl;
import de.uni_koblenz.jgralab.impl.array.EdgeImpl;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;

import de.uni_koblenz.jgralab.greql2.schema.Greql2Aggregation;
import de.uni_koblenz.jgralab.greql2.schema.IsDefinitionOf;
import de.uni_koblenz.jgralab.greql2.schema.SourcePosition;

import java.io.IOException;

public class ReversedIsDefinitionOfImpl extends ReversedAggregationImpl implements Aggregation, Greql2Aggregation, IsDefinitionOf {

	ReversedIsDefinitionOfImpl(EdgeImpl e, Graph g) {
		super(e, g);
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		return ((IsDefinitionOf)normalEdge).getAttribute(attributeName);
	}

	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		((IsDefinitionOf)normalEdge).setAttribute(attributeName, data);
	}

	public java.util.List<SourcePosition> getSourcePositions() {
		return ((IsDefinitionOf)normalEdge).getSourcePositions();
	}

	public void setSourcePositions(java.util.List<SourcePosition> sourcePositions) {
		((IsDefinitionOf)normalEdge).setSourcePositions(sourcePositions);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public Greql2Aggregation getNextGreql2AggregationInGraph() {
		return ((Greql2Aggregation)normalEdge).getNextGreql2AggregationInGraph();
	}

	public IsDefinitionOf getNextIsDefinitionOfInGraph() {
		return ((IsDefinitionOf)normalEdge).getNextIsDefinitionOfInGraph();
	}

	public IsDefinitionOf getNextIsDefinitionOfInGraph(boolean noSubClasses) {
		return ((IsDefinitionOf)normalEdge).getNextIsDefinitionOfInGraph(noSubClasses);
	}

	public Greql2Aggregation getNextGreql2Aggregation() {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class);
	}

	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation) {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class, orientation);
	}

	public IsDefinitionOf getNextIsDefinitionOf() {
		return (IsDefinitionOf)getNextEdgeOfClass(IsDefinitionOf.class);
	}

	public IsDefinitionOf getNextIsDefinitionOf(EdgeDirection orientation) {
		return (IsDefinitionOf)getNextEdgeOfClass(IsDefinitionOf.class, orientation);
	}

	public IsDefinitionOf getNextIsDefinitionOf(boolean noSubClasses) {
		return (IsDefinitionOf)getNextEdgeOfClass(IsDefinitionOf.class, noSubClasses);
	}

	public IsDefinitionOf getNextIsDefinitionOf(EdgeDirection orientation, boolean noSubClasses) {
		return (IsDefinitionOf)getNextEdgeOfClass(IsDefinitionOf.class, orientation, noSubClasses);
	}

}
