/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema.impl;

import de.uni_koblenz.jgralab.impl.array.ReversedAggregationImpl;
import de.uni_koblenz.jgralab.impl.array.EdgeImpl;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;

import de.uni_koblenz.jgralab.greql2.schema.Greql2Aggregation;
import de.uni_koblenz.jgralab.greql2.schema.IsEdgeOrVertexExprOf;
import de.uni_koblenz.jgralab.greql2.schema.SourcePosition;

import java.io.IOException;

public class ReversedIsEdgeOrVertexExprOfImpl extends ReversedAggregationImpl implements Aggregation, Greql2Aggregation, IsEdgeOrVertexExprOf {

	ReversedIsEdgeOrVertexExprOfImpl(EdgeImpl e, Graph g) {
		super(e, g);
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		return ((IsEdgeOrVertexExprOf)normalEdge).getAttribute(attributeName);
	}

	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		((IsEdgeOrVertexExprOf)normalEdge).setAttribute(attributeName, data);
	}

	public java.util.List<SourcePosition> getSourcePositions() {
		return ((IsEdgeOrVertexExprOf)normalEdge).getSourcePositions();
	}

	public void setSourcePositions(java.util.List<SourcePosition> sourcePositions) {
		((IsEdgeOrVertexExprOf)normalEdge).setSourcePositions(sourcePositions);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public Greql2Aggregation getNextGreql2AggregationInGraph() {
		return ((Greql2Aggregation)normalEdge).getNextGreql2AggregationInGraph();
	}

	public IsEdgeOrVertexExprOf getNextIsEdgeOrVertexExprOfInGraph() {
		return ((IsEdgeOrVertexExprOf)normalEdge).getNextIsEdgeOrVertexExprOfInGraph();
	}

	public IsEdgeOrVertexExprOf getNextIsEdgeOrVertexExprOfInGraph(boolean noSubClasses) {
		return ((IsEdgeOrVertexExprOf)normalEdge).getNextIsEdgeOrVertexExprOfInGraph(noSubClasses);
	}

	public Greql2Aggregation getNextGreql2Aggregation() {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class);
	}

	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation) {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class, orientation);
	}

	public IsEdgeOrVertexExprOf getNextIsEdgeOrVertexExprOf() {
		return (IsEdgeOrVertexExprOf)getNextEdgeOfClass(IsEdgeOrVertexExprOf.class);
	}

	public IsEdgeOrVertexExprOf getNextIsEdgeOrVertexExprOf(EdgeDirection orientation) {
		return (IsEdgeOrVertexExprOf)getNextEdgeOfClass(IsEdgeOrVertexExprOf.class, orientation);
	}

	public IsEdgeOrVertexExprOf getNextIsEdgeOrVertexExprOf(boolean noSubClasses) {
		return (IsEdgeOrVertexExprOf)getNextEdgeOfClass(IsEdgeOrVertexExprOf.class, noSubClasses);
	}

	public IsEdgeOrVertexExprOf getNextIsEdgeOrVertexExprOf(EdgeDirection orientation, boolean noSubClasses) {
		return (IsEdgeOrVertexExprOf)getNextEdgeOfClass(IsEdgeOrVertexExprOf.class, orientation, noSubClasses);
	}

}
