/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema.impl;

import de.uni_koblenz.jgralab.impl.array.ReversedAggregationImpl;
import de.uni_koblenz.jgralab.impl.array.EdgeImpl;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;

import de.uni_koblenz.jgralab.greql2.schema.Greql2Aggregation;
import de.uni_koblenz.jgralab.greql2.schema.IsFunctionIdOf;
import de.uni_koblenz.jgralab.greql2.schema.SourcePosition;

import java.io.IOException;

public class ReversedIsFunctionIdOfImpl extends ReversedAggregationImpl implements Aggregation, Greql2Aggregation, IsFunctionIdOf {

	ReversedIsFunctionIdOfImpl(EdgeImpl e, Graph g) {
		super(e, g);
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		return ((IsFunctionIdOf)normalEdge).getAttribute(attributeName);
	}

	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		((IsFunctionIdOf)normalEdge).setAttribute(attributeName, data);
	}

	public java.util.List<SourcePosition> getSourcePositions() {
		return ((IsFunctionIdOf)normalEdge).getSourcePositions();
	}

	public void setSourcePositions(java.util.List<SourcePosition> sourcePositions) {
		((IsFunctionIdOf)normalEdge).setSourcePositions(sourcePositions);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public Greql2Aggregation getNextGreql2AggregationInGraph() {
		return ((Greql2Aggregation)normalEdge).getNextGreql2AggregationInGraph();
	}

	public IsFunctionIdOf getNextIsFunctionIdOfInGraph() {
		return ((IsFunctionIdOf)normalEdge).getNextIsFunctionIdOfInGraph();
	}

	public IsFunctionIdOf getNextIsFunctionIdOfInGraph(boolean noSubClasses) {
		return ((IsFunctionIdOf)normalEdge).getNextIsFunctionIdOfInGraph(noSubClasses);
	}

	public Greql2Aggregation getNextGreql2Aggregation() {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class);
	}

	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation) {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class, orientation);
	}

	public IsFunctionIdOf getNextIsFunctionIdOf() {
		return (IsFunctionIdOf)getNextEdgeOfClass(IsFunctionIdOf.class);
	}

	public IsFunctionIdOf getNextIsFunctionIdOf(EdgeDirection orientation) {
		return (IsFunctionIdOf)getNextEdgeOfClass(IsFunctionIdOf.class, orientation);
	}

	public IsFunctionIdOf getNextIsFunctionIdOf(boolean noSubClasses) {
		return (IsFunctionIdOf)getNextEdgeOfClass(IsFunctionIdOf.class, noSubClasses);
	}

	public IsFunctionIdOf getNextIsFunctionIdOf(EdgeDirection orientation, boolean noSubClasses) {
		return (IsFunctionIdOf)getNextEdgeOfClass(IsFunctionIdOf.class, orientation, noSubClasses);
	}

}
