/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema.impl;

import de.uni_koblenz.jgralab.impl.array.ReversedAggregationImpl;
import de.uni_koblenz.jgralab.impl.array.EdgeImpl;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;

import de.uni_koblenz.jgralab.greql2.schema.Greql2Aggregation;
import de.uni_koblenz.jgralab.greql2.schema.IsEdgeRestrOf;
import de.uni_koblenz.jgralab.greql2.schema.SourcePosition;

import java.io.IOException;

public class ReversedIsEdgeRestrOfImpl extends ReversedAggregationImpl implements Aggregation, Greql2Aggregation, IsEdgeRestrOf {

	ReversedIsEdgeRestrOfImpl(EdgeImpl e, Graph g) {
		super(e, g);
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		return ((IsEdgeRestrOf)normalEdge).getAttribute(attributeName);
	}

	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		((IsEdgeRestrOf)normalEdge).setAttribute(attributeName, data);
	}

	public java.util.List<SourcePosition> getSourcePositions() {
		return ((IsEdgeRestrOf)normalEdge).getSourcePositions();
	}

	public void setSourcePositions(java.util.List<SourcePosition> sourcePositions) {
		((IsEdgeRestrOf)normalEdge).setSourcePositions(sourcePositions);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public Greql2Aggregation getNextGreql2AggregationInGraph() {
		return ((Greql2Aggregation)normalEdge).getNextGreql2AggregationInGraph();
	}

	public IsEdgeRestrOf getNextIsEdgeRestrOfInGraph() {
		return ((IsEdgeRestrOf)normalEdge).getNextIsEdgeRestrOfInGraph();
	}

	public IsEdgeRestrOf getNextIsEdgeRestrOfInGraph(boolean noSubClasses) {
		return ((IsEdgeRestrOf)normalEdge).getNextIsEdgeRestrOfInGraph(noSubClasses);
	}

	public Greql2Aggregation getNextGreql2Aggregation() {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class);
	}

	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation) {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class, orientation);
	}

	public IsEdgeRestrOf getNextIsEdgeRestrOf() {
		return (IsEdgeRestrOf)getNextEdgeOfClass(IsEdgeRestrOf.class);
	}

	public IsEdgeRestrOf getNextIsEdgeRestrOf(EdgeDirection orientation) {
		return (IsEdgeRestrOf)getNextEdgeOfClass(IsEdgeRestrOf.class, orientation);
	}

	public IsEdgeRestrOf getNextIsEdgeRestrOf(boolean noSubClasses) {
		return (IsEdgeRestrOf)getNextEdgeOfClass(IsEdgeRestrOf.class, noSubClasses);
	}

	public IsEdgeRestrOf getNextIsEdgeRestrOf(EdgeDirection orientation, boolean noSubClasses) {
		return (IsEdgeRestrOf)getNextEdgeOfClass(IsEdgeRestrOf.class, orientation, noSubClasses);
	}

}
