/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema.impl;

import de.uni_koblenz.jgralab.impl.array.ReversedAggregationImpl;
import de.uni_koblenz.jgralab.impl.array.EdgeImpl;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;

import de.uni_koblenz.jgralab.greql2.schema.Greql2Aggregation;
import de.uni_koblenz.jgralab.greql2.schema.IsVarOf;
import de.uni_koblenz.jgralab.greql2.schema.SourcePosition;

import java.io.IOException;

public class ReversedIsVarOfImpl extends ReversedAggregationImpl implements Aggregation, Greql2Aggregation, IsVarOf {

	ReversedIsVarOfImpl(EdgeImpl e, Graph g) {
		super(e, g);
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		return ((IsVarOf)normalEdge).getAttribute(attributeName);
	}

	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		((IsVarOf)normalEdge).setAttribute(attributeName, data);
	}

	public java.util.List<SourcePosition> getSourcePositions() {
		return ((IsVarOf)normalEdge).getSourcePositions();
	}

	public void setSourcePositions(java.util.List<SourcePosition> sourcePositions) {
		((IsVarOf)normalEdge).setSourcePositions(sourcePositions);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public Greql2Aggregation getNextGreql2AggregationInGraph() {
		return ((Greql2Aggregation)normalEdge).getNextGreql2AggregationInGraph();
	}

	public IsVarOf getNextIsVarOfInGraph() {
		return ((IsVarOf)normalEdge).getNextIsVarOfInGraph();
	}

	public IsVarOf getNextIsVarOfInGraph(boolean noSubClasses) {
		return ((IsVarOf)normalEdge).getNextIsVarOfInGraph(noSubClasses);
	}

	public Greql2Aggregation getNextGreql2Aggregation() {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class);
	}

	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation) {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class, orientation);
	}

	public IsVarOf getNextIsVarOf() {
		return (IsVarOf)getNextEdgeOfClass(IsVarOf.class);
	}

	public IsVarOf getNextIsVarOf(EdgeDirection orientation) {
		return (IsVarOf)getNextEdgeOfClass(IsVarOf.class, orientation);
	}

	public IsVarOf getNextIsVarOf(boolean noSubClasses) {
		return (IsVarOf)getNextEdgeOfClass(IsVarOf.class, noSubClasses);
	}

	public IsVarOf getNextIsVarOf(EdgeDirection orientation, boolean noSubClasses) {
		return (IsVarOf)getNextEdgeOfClass(IsVarOf.class, orientation, noSubClasses);
	}

}
