/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema.impl;

import de.uni_koblenz.jgralab.impl.array.ReversedAggregationImpl;
import de.uni_koblenz.jgralab.impl.array.EdgeImpl;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;

import de.uni_koblenz.jgralab.greql2.schema.Greql2Aggregation;
import de.uni_koblenz.jgralab.greql2.schema.IsPathDescriptionOf;
import de.uni_koblenz.jgralab.greql2.schema.IsSequenceElementOf;
import de.uni_koblenz.jgralab.greql2.schema.SourcePosition;

import java.io.IOException;

public class ReversedIsSequenceElementOfImpl extends ReversedAggregationImpl implements Aggregation, Greql2Aggregation, IsPathDescriptionOf, IsSequenceElementOf {

	ReversedIsSequenceElementOfImpl(EdgeImpl e, Graph g) {
		super(e, g);
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		return ((IsSequenceElementOf)normalEdge).getAttribute(attributeName);
	}

	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		((IsSequenceElementOf)normalEdge).setAttribute(attributeName, data);
	}

	public java.util.List<SourcePosition> getSourcePositions() {
		return ((IsSequenceElementOf)normalEdge).getSourcePositions();
	}

	public void setSourcePositions(java.util.List<SourcePosition> sourcePositions) {
		((IsSequenceElementOf)normalEdge).setSourcePositions(sourcePositions);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public Greql2Aggregation getNextGreql2AggregationInGraph() {
		return ((Greql2Aggregation)normalEdge).getNextGreql2AggregationInGraph();
	}

	public IsPathDescriptionOf getNextIsPathDescriptionOfInGraph() {
		return ((IsPathDescriptionOf)normalEdge).getNextIsPathDescriptionOfInGraph();
	}

	public IsSequenceElementOf getNextIsSequenceElementOfInGraph() {
		return ((IsSequenceElementOf)normalEdge).getNextIsSequenceElementOfInGraph();
	}

	public IsSequenceElementOf getNextIsSequenceElementOfInGraph(boolean noSubClasses) {
		return ((IsSequenceElementOf)normalEdge).getNextIsSequenceElementOfInGraph(noSubClasses);
	}

	public Greql2Aggregation getNextGreql2Aggregation() {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class);
	}

	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation) {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class, orientation);
	}

	public IsPathDescriptionOf getNextIsPathDescriptionOf() {
		return (IsPathDescriptionOf)getNextEdgeOfClass(IsPathDescriptionOf.class);
	}

	public IsPathDescriptionOf getNextIsPathDescriptionOf(EdgeDirection orientation) {
		return (IsPathDescriptionOf)getNextEdgeOfClass(IsPathDescriptionOf.class, orientation);
	}

	public IsSequenceElementOf getNextIsSequenceElementOf() {
		return (IsSequenceElementOf)getNextEdgeOfClass(IsSequenceElementOf.class);
	}

	public IsSequenceElementOf getNextIsSequenceElementOf(EdgeDirection orientation) {
		return (IsSequenceElementOf)getNextEdgeOfClass(IsSequenceElementOf.class, orientation);
	}

	public IsSequenceElementOf getNextIsSequenceElementOf(boolean noSubClasses) {
		return (IsSequenceElementOf)getNextEdgeOfClass(IsSequenceElementOf.class, noSubClasses);
	}

	public IsSequenceElementOf getNextIsSequenceElementOf(EdgeDirection orientation, boolean noSubClasses) {
		return (IsSequenceElementOf)getNextEdgeOfClass(IsSequenceElementOf.class, orientation, noSubClasses);
	}

}
