/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema.impl;

import de.uni_koblenz.jgralab.impl.array.ReversedAggregationImpl;
import de.uni_koblenz.jgralab.impl.array.EdgeImpl;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;

import de.uni_koblenz.jgralab.greql2.schema.Greql2Aggregation;
import de.uni_koblenz.jgralab.greql2.schema.IsArgumentOf;
import de.uni_koblenz.jgralab.greql2.schema.SourcePosition;

import java.io.IOException;

public class ReversedIsArgumentOfImpl extends ReversedAggregationImpl implements Aggregation, Greql2Aggregation, IsArgumentOf {

	ReversedIsArgumentOfImpl(EdgeImpl e, Graph g) {
		super(e, g);
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		return ((IsArgumentOf)normalEdge).getAttribute(attributeName);
	}

	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		((IsArgumentOf)normalEdge).setAttribute(attributeName, data);
	}

	public java.util.List<SourcePosition> getSourcePositions() {
		return ((IsArgumentOf)normalEdge).getSourcePositions();
	}

	public void setSourcePositions(java.util.List<SourcePosition> sourcePositions) {
		((IsArgumentOf)normalEdge).setSourcePositions(sourcePositions);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public Greql2Aggregation getNextGreql2AggregationInGraph() {
		return ((Greql2Aggregation)normalEdge).getNextGreql2AggregationInGraph();
	}

	public IsArgumentOf getNextIsArgumentOfInGraph() {
		return ((IsArgumentOf)normalEdge).getNextIsArgumentOfInGraph();
	}

	public IsArgumentOf getNextIsArgumentOfInGraph(boolean noSubClasses) {
		return ((IsArgumentOf)normalEdge).getNextIsArgumentOfInGraph(noSubClasses);
	}

	public Greql2Aggregation getNextGreql2Aggregation() {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class);
	}

	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation) {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class, orientation);
	}

	public IsArgumentOf getNextIsArgumentOf() {
		return (IsArgumentOf)getNextEdgeOfClass(IsArgumentOf.class);
	}

	public IsArgumentOf getNextIsArgumentOf(EdgeDirection orientation) {
		return (IsArgumentOf)getNextEdgeOfClass(IsArgumentOf.class, orientation);
	}

	public IsArgumentOf getNextIsArgumentOf(boolean noSubClasses) {
		return (IsArgumentOf)getNextEdgeOfClass(IsArgumentOf.class, noSubClasses);
	}

	public IsArgumentOf getNextIsArgumentOf(EdgeDirection orientation, boolean noSubClasses) {
		return (IsArgumentOf)getNextEdgeOfClass(IsArgumentOf.class, orientation, noSubClasses);
	}

}
