/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema.impl;

import de.uni_koblenz.jgralab.impl.array.ReversedAggregationImpl;
import de.uni_koblenz.jgralab.impl.array.EdgeImpl;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;

import de.uni_koblenz.jgralab.greql2.schema.Greql2Aggregation;
import de.uni_koblenz.jgralab.greql2.schema.IsQueryExprOf;
import de.uni_koblenz.jgralab.greql2.schema.SourcePosition;

import java.io.IOException;

public class ReversedIsQueryExprOfImpl extends ReversedAggregationImpl implements Aggregation, Greql2Aggregation, IsQueryExprOf {

	ReversedIsQueryExprOfImpl(EdgeImpl e, Graph g) {
		super(e, g);
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		return ((IsQueryExprOf)normalEdge).getAttribute(attributeName);
	}

	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		((IsQueryExprOf)normalEdge).setAttribute(attributeName, data);
	}

	public java.util.List<SourcePosition> getSourcePositions() {
		return ((IsQueryExprOf)normalEdge).getSourcePositions();
	}

	public void setSourcePositions(java.util.List<SourcePosition> sourcePositions) {
		((IsQueryExprOf)normalEdge).setSourcePositions(sourcePositions);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public Greql2Aggregation getNextGreql2AggregationInGraph() {
		return ((Greql2Aggregation)normalEdge).getNextGreql2AggregationInGraph();
	}

	public IsQueryExprOf getNextIsQueryExprOfInGraph() {
		return ((IsQueryExprOf)normalEdge).getNextIsQueryExprOfInGraph();
	}

	public IsQueryExprOf getNextIsQueryExprOfInGraph(boolean noSubClasses) {
		return ((IsQueryExprOf)normalEdge).getNextIsQueryExprOfInGraph(noSubClasses);
	}

	public Greql2Aggregation getNextGreql2Aggregation() {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class);
	}

	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation) {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class, orientation);
	}

	public IsQueryExprOf getNextIsQueryExprOf() {
		return (IsQueryExprOf)getNextEdgeOfClass(IsQueryExprOf.class);
	}

	public IsQueryExprOf getNextIsQueryExprOf(EdgeDirection orientation) {
		return (IsQueryExprOf)getNextEdgeOfClass(IsQueryExprOf.class, orientation);
	}

	public IsQueryExprOf getNextIsQueryExprOf(boolean noSubClasses) {
		return (IsQueryExprOf)getNextEdgeOfClass(IsQueryExprOf.class, noSubClasses);
	}

	public IsQueryExprOf getNextIsQueryExprOf(EdgeDirection orientation, boolean noSubClasses) {
		return (IsQueryExprOf)getNextEdgeOfClass(IsQueryExprOf.class, orientation, noSubClasses);
	}

}
