/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema.impl;

import de.uni_koblenz.jgralab.impl.array.ReversedAggregationImpl;
import de.uni_koblenz.jgralab.impl.array.EdgeImpl;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;

import de.uni_koblenz.jgralab.greql2.schema.Greql2Aggregation;
import de.uni_koblenz.jgralab.greql2.schema.IsIntermediateVertexOf;
import de.uni_koblenz.jgralab.greql2.schema.SourcePosition;

import java.io.IOException;

public class ReversedIsIntermediateVertexOfImpl extends ReversedAggregationImpl implements Aggregation, Greql2Aggregation, IsIntermediateVertexOf {

	ReversedIsIntermediateVertexOfImpl(EdgeImpl e, Graph g) {
		super(e, g);
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		return ((IsIntermediateVertexOf)normalEdge).getAttribute(attributeName);
	}

	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		((IsIntermediateVertexOf)normalEdge).setAttribute(attributeName, data);
	}

	public java.util.List<SourcePosition> getSourcePositions() {
		return ((IsIntermediateVertexOf)normalEdge).getSourcePositions();
	}

	public void setSourcePositions(java.util.List<SourcePosition> sourcePositions) {
		((IsIntermediateVertexOf)normalEdge).setSourcePositions(sourcePositions);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public Greql2Aggregation getNextGreql2AggregationInGraph() {
		return ((Greql2Aggregation)normalEdge).getNextGreql2AggregationInGraph();
	}

	public IsIntermediateVertexOf getNextIsIntermediateVertexOfInGraph() {
		return ((IsIntermediateVertexOf)normalEdge).getNextIsIntermediateVertexOfInGraph();
	}

	public IsIntermediateVertexOf getNextIsIntermediateVertexOfInGraph(boolean noSubClasses) {
		return ((IsIntermediateVertexOf)normalEdge).getNextIsIntermediateVertexOfInGraph(noSubClasses);
	}

	public Greql2Aggregation getNextGreql2Aggregation() {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class);
	}

	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation) {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class, orientation);
	}

	public IsIntermediateVertexOf getNextIsIntermediateVertexOf() {
		return (IsIntermediateVertexOf)getNextEdgeOfClass(IsIntermediateVertexOf.class);
	}

	public IsIntermediateVertexOf getNextIsIntermediateVertexOf(EdgeDirection orientation) {
		return (IsIntermediateVertexOf)getNextEdgeOfClass(IsIntermediateVertexOf.class, orientation);
	}

	public IsIntermediateVertexOf getNextIsIntermediateVertexOf(boolean noSubClasses) {
		return (IsIntermediateVertexOf)getNextEdgeOfClass(IsIntermediateVertexOf.class, noSubClasses);
	}

	public IsIntermediateVertexOf getNextIsIntermediateVertexOf(EdgeDirection orientation, boolean noSubClasses) {
		return (IsIntermediateVertexOf)getNextEdgeOfClass(IsIntermediateVertexOf.class, orientation, noSubClasses);
	}

}
