/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema.impl;

import de.uni_koblenz.jgralab.impl.array.ReversedAggregationImpl;
import de.uni_koblenz.jgralab.impl.array.EdgeImpl;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;

import de.uni_koblenz.jgralab.greql2.schema.Greql2Aggregation;
import de.uni_koblenz.jgralab.greql2.schema.IsGoalRestrOf;
import de.uni_koblenz.jgralab.greql2.schema.SourcePosition;

import java.io.IOException;

public class ReversedIsGoalRestrOfImpl extends ReversedAggregationImpl implements Aggregation, Greql2Aggregation, IsGoalRestrOf {

	ReversedIsGoalRestrOfImpl(EdgeImpl e, Graph g) {
		super(e, g);
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		return ((IsGoalRestrOf)normalEdge).getAttribute(attributeName);
	}

	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		((IsGoalRestrOf)normalEdge).setAttribute(attributeName, data);
	}

	public java.util.List<SourcePosition> getSourcePositions() {
		return ((IsGoalRestrOf)normalEdge).getSourcePositions();
	}

	public void setSourcePositions(java.util.List<SourcePosition> sourcePositions) {
		((IsGoalRestrOf)normalEdge).setSourcePositions(sourcePositions);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public Greql2Aggregation getNextGreql2AggregationInGraph() {
		return ((Greql2Aggregation)normalEdge).getNextGreql2AggregationInGraph();
	}

	public IsGoalRestrOf getNextIsGoalRestrOfInGraph() {
		return ((IsGoalRestrOf)normalEdge).getNextIsGoalRestrOfInGraph();
	}

	public IsGoalRestrOf getNextIsGoalRestrOfInGraph(boolean noSubClasses) {
		return ((IsGoalRestrOf)normalEdge).getNextIsGoalRestrOfInGraph(noSubClasses);
	}

	public Greql2Aggregation getNextGreql2Aggregation() {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class);
	}

	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation) {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class, orientation);
	}

	public IsGoalRestrOf getNextIsGoalRestrOf() {
		return (IsGoalRestrOf)getNextEdgeOfClass(IsGoalRestrOf.class);
	}

	public IsGoalRestrOf getNextIsGoalRestrOf(EdgeDirection orientation) {
		return (IsGoalRestrOf)getNextEdgeOfClass(IsGoalRestrOf.class, orientation);
	}

	public IsGoalRestrOf getNextIsGoalRestrOf(boolean noSubClasses) {
		return (IsGoalRestrOf)getNextEdgeOfClass(IsGoalRestrOf.class, noSubClasses);
	}

	public IsGoalRestrOf getNextIsGoalRestrOf(EdgeDirection orientation, boolean noSubClasses) {
		return (IsGoalRestrOf)getNextEdgeOfClass(IsGoalRestrOf.class, orientation, noSubClasses);
	}

}
