/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema.impl;

import de.uni_koblenz.jgralab.impl.array.ReversedAggregationImpl;
import de.uni_koblenz.jgralab.impl.array.EdgeImpl;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;

import de.uni_koblenz.jgralab.greql2.schema.Greql2Aggregation;
import de.uni_koblenz.jgralab.greql2.schema.IsSymbolOf;
import de.uni_koblenz.jgralab.greql2.schema.SourcePosition;

import java.io.IOException;

public class ReversedIsSymbolOfImpl extends ReversedAggregationImpl implements Aggregation, Greql2Aggregation, IsSymbolOf {

	ReversedIsSymbolOfImpl(EdgeImpl e, Graph g) {
		super(e, g);
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		return ((IsSymbolOf)normalEdge).getAttribute(attributeName);
	}

	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		((IsSymbolOf)normalEdge).setAttribute(attributeName, data);
	}

	public java.util.List<SourcePosition> getSourcePositions() {
		return ((IsSymbolOf)normalEdge).getSourcePositions();
	}

	public void setSourcePositions(java.util.List<SourcePosition> sourcePositions) {
		((IsSymbolOf)normalEdge).setSourcePositions(sourcePositions);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public Greql2Aggregation getNextGreql2AggregationInGraph() {
		return ((Greql2Aggregation)normalEdge).getNextGreql2AggregationInGraph();
	}

	public IsSymbolOf getNextIsSymbolOfInGraph() {
		return ((IsSymbolOf)normalEdge).getNextIsSymbolOfInGraph();
	}

	public IsSymbolOf getNextIsSymbolOfInGraph(boolean noSubClasses) {
		return ((IsSymbolOf)normalEdge).getNextIsSymbolOfInGraph(noSubClasses);
	}

	public Greql2Aggregation getNextGreql2Aggregation() {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class);
	}

	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation) {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class, orientation);
	}

	public IsSymbolOf getNextIsSymbolOf() {
		return (IsSymbolOf)getNextEdgeOfClass(IsSymbolOf.class);
	}

	public IsSymbolOf getNextIsSymbolOf(EdgeDirection orientation) {
		return (IsSymbolOf)getNextEdgeOfClass(IsSymbolOf.class, orientation);
	}

	public IsSymbolOf getNextIsSymbolOf(boolean noSubClasses) {
		return (IsSymbolOf)getNextEdgeOfClass(IsSymbolOf.class, noSubClasses);
	}

	public IsSymbolOf getNextIsSymbolOf(EdgeDirection orientation, boolean noSubClasses) {
		return (IsSymbolOf)getNextEdgeOfClass(IsSymbolOf.class, orientation, noSubClasses);
	}

}
