/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema.impl;

import de.uni_koblenz.jgralab.impl.array.ReversedAggregationImpl;
import de.uni_koblenz.jgralab.impl.array.EdgeImpl;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;

import de.uni_koblenz.jgralab.greql2.schema.Greql2Aggregation;
import de.uni_koblenz.jgralab.greql2.schema.IsProductionOf;
import de.uni_koblenz.jgralab.greql2.schema.SourcePosition;

import java.io.IOException;

public class ReversedIsProductionOfImpl extends ReversedAggregationImpl implements Aggregation, Greql2Aggregation, IsProductionOf {

	ReversedIsProductionOfImpl(EdgeImpl e, Graph g) {
		super(e, g);
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		return ((IsProductionOf)normalEdge).getAttribute(attributeName);
	}

	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		((IsProductionOf)normalEdge).setAttribute(attributeName, data);
	}

	public java.util.List<SourcePosition> getSourcePositions() {
		return ((IsProductionOf)normalEdge).getSourcePositions();
	}

	public void setSourcePositions(java.util.List<SourcePosition> sourcePositions) {
		((IsProductionOf)normalEdge).setSourcePositions(sourcePositions);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public Greql2Aggregation getNextGreql2AggregationInGraph() {
		return ((Greql2Aggregation)normalEdge).getNextGreql2AggregationInGraph();
	}

	public IsProductionOf getNextIsProductionOfInGraph() {
		return ((IsProductionOf)normalEdge).getNextIsProductionOfInGraph();
	}

	public IsProductionOf getNextIsProductionOfInGraph(boolean noSubClasses) {
		return ((IsProductionOf)normalEdge).getNextIsProductionOfInGraph(noSubClasses);
	}

	public Greql2Aggregation getNextGreql2Aggregation() {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class);
	}

	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation) {
		return (Greql2Aggregation)getNextEdgeOfClass(Greql2Aggregation.class, orientation);
	}

	public IsProductionOf getNextIsProductionOf() {
		return (IsProductionOf)getNextEdgeOfClass(IsProductionOf.class);
	}

	public IsProductionOf getNextIsProductionOf(EdgeDirection orientation) {
		return (IsProductionOf)getNextEdgeOfClass(IsProductionOf.class, orientation);
	}

	public IsProductionOf getNextIsProductionOf(boolean noSubClasses) {
		return (IsProductionOf)getNextEdgeOfClass(IsProductionOf.class, noSubClasses);
	}

	public IsProductionOf getNextIsProductionOf(EdgeDirection orientation, boolean noSubClasses) {
		return (IsProductionOf)getNextEdgeOfClass(IsProductionOf.class, orientation, noSubClasses);
	}

}
