/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema.impl;

import de.uni_koblenz.jgralab.impl.array.VertexImpl;
import de.uni_koblenz.jgralab.impl.IncidenceIterable;

import de.uni_koblenz.jgralab.VertexClass;
import de.uni_koblenz.jgralab.AttributedElement;
import de.uni_koblenz.jgralab.Edge;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.EdgeVertexPair;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;
import de.uni_koblenz.jgralab.Vertex;

import de.uni_koblenz.jgralab.greql2.schema.Greql2Aggregation;
import de.uni_koblenz.jgralab.greql2.schema.Greql2Vertex;
import de.uni_koblenz.jgralab.greql2.schema.IsBoundExprOf;
import de.uni_koblenz.jgralab.greql2.schema.IsDeclaredVarOf;
import de.uni_koblenz.jgralab.greql2.schema.IsSimpleDeclOf;
import de.uni_koblenz.jgralab.greql2.schema.IsTypeExprOf;
import de.uni_koblenz.jgralab.greql2.schema.IsTypeExprOfDeclaration;
import de.uni_koblenz.jgralab.greql2.schema.SimpleDeclaration;

import java.io.IOException;
import java.util.HashSet;
import java.util.Set;

public class SimpleDeclarationImpl extends VertexImpl implements Greql2Vertex, SimpleDeclaration, Vertex {

	public SimpleDeclarationImpl(int id, Graph g) {
		super(id, g, (VertexClass)g.getGraphClass().getGraphElementClass("SimpleDeclaration"));
	}

	public Class<? extends AttributedElement> getM1Class() {
		return SimpleDeclaration.class;
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		throw new NoSuchFieldException("SimpleDeclaration doesn't contain an attribute " + attributeName);
	}

	@SuppressWarnings("unchecked")
	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		throw new NoSuchFieldException("SimpleDeclaration doesn't contain an attribute " + attributeName);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	/* add all valid from edges */
	private static Set<Class<? extends Edge>> validFromEdges = new HashSet<Class<? extends Edge>>();
	
	/* (non-Javadoc)
	 * @see jgralab.Vertex:isValidAlpha()
	 */
	public boolean isValidAlpha(Edge edge) {
		return validFromEdges.contains(edge.getClass());
	}
	
	{

		validFromEdges.add(IsSimpleDeclOfImpl.class);

	}
	
	/* add all valid to edges */
	private static Set<Class<? extends Edge>> validToEdges = new HashSet<Class<? extends Edge>>();
	
	/* (non-Javadoc)
	 * @see jgralab.Vertex:isValidOemga()
	 */
	public boolean isValidOmega(Edge edge) {
		return validToEdges.contains(edge.getClass());
	}
	
	{

		validToEdges.add(IsTypeExprOfDeclarationImpl.class);

		validToEdges.add(IsDeclaredVarOfImpl.class);

	}

	public Greql2Vertex getNextGreql2Vertex() {
		return (Greql2Vertex)getNextVertexOfClass(Greql2Vertex.class);
	}

	public SimpleDeclaration getNextSimpleDeclaration() {
		return (SimpleDeclaration)getNextVertexOfClass(SimpleDeclaration.class);
	}

	public SimpleDeclaration getNextSimpleDeclaration(boolean noSubClasses) {
		return (SimpleDeclaration)getNextVertexOfClass(SimpleDeclaration.class, noSubClasses);
	}

	public IsBoundExprOf getFirstIsBoundExprOf() {
		return (IsBoundExprOf)getFirstEdgeOfClass(IsBoundExprOf.class);
	}

	public IsBoundExprOf getFirstIsBoundExprOf(EdgeDirection orientation) {
		return (IsBoundExprOf)getFirstEdgeOfClass(IsBoundExprOf.class, orientation);
	}

	public Greql2Aggregation getFirstGreql2Aggregation() {
		return (Greql2Aggregation)getFirstEdgeOfClass(Greql2Aggregation.class);
	}

	public Greql2Aggregation getFirstGreql2Aggregation(EdgeDirection orientation) {
		return (Greql2Aggregation)getFirstEdgeOfClass(Greql2Aggregation.class, orientation);
	}

	public IsTypeExprOf getFirstIsTypeExprOf() {
		return (IsTypeExprOf)getFirstEdgeOfClass(IsTypeExprOf.class);
	}

	public IsTypeExprOf getFirstIsTypeExprOf(EdgeDirection orientation) {
		return (IsTypeExprOf)getFirstEdgeOfClass(IsTypeExprOf.class, orientation);
	}

	public IsTypeExprOfDeclaration getFirstIsTypeExprOfDeclaration() {
		return (IsTypeExprOfDeclaration)getFirstEdgeOfClass(IsTypeExprOfDeclaration.class);
	}

	public IsTypeExprOfDeclaration getFirstIsTypeExprOfDeclaration(EdgeDirection orientation) {
		return (IsTypeExprOfDeclaration)getFirstEdgeOfClass(IsTypeExprOfDeclaration.class, orientation);
	}

	public IsTypeExprOfDeclaration getFirstIsTypeExprOfDeclaration(boolean noSubClasses) {
		return (IsTypeExprOfDeclaration)getFirstEdgeOfClass(IsTypeExprOfDeclaration.class, noSubClasses);
	}

	public IsTypeExprOfDeclaration getFirstIsTypeExprOfDeclaration(EdgeDirection orientation, boolean noSubClasses) {
		return (IsTypeExprOfDeclaration)getFirstEdgeOfClass(IsTypeExprOfDeclaration.class, orientation, noSubClasses);
	}

	public IsDeclaredVarOf getFirstIsDeclaredVarOf() {
		return (IsDeclaredVarOf)getFirstEdgeOfClass(IsDeclaredVarOf.class);
	}

	public IsDeclaredVarOf getFirstIsDeclaredVarOf(EdgeDirection orientation) {
		return (IsDeclaredVarOf)getFirstEdgeOfClass(IsDeclaredVarOf.class, orientation);
	}

	public IsDeclaredVarOf getFirstIsDeclaredVarOf(boolean noSubClasses) {
		return (IsDeclaredVarOf)getFirstEdgeOfClass(IsDeclaredVarOf.class, noSubClasses);
	}

	public IsDeclaredVarOf getFirstIsDeclaredVarOf(EdgeDirection orientation, boolean noSubClasses) {
		return (IsDeclaredVarOf)getFirstEdgeOfClass(IsDeclaredVarOf.class, orientation, noSubClasses);
	}

	public IsSimpleDeclOf getFirstIsSimpleDeclOf() {
		return (IsSimpleDeclOf)getFirstEdgeOfClass(IsSimpleDeclOf.class);
	}

	public IsSimpleDeclOf getFirstIsSimpleDeclOf(EdgeDirection orientation) {
		return (IsSimpleDeclOf)getFirstEdgeOfClass(IsSimpleDeclOf.class, orientation);
	}

	public IsSimpleDeclOf getFirstIsSimpleDeclOf(boolean noSubClasses) {
		return (IsSimpleDeclOf)getFirstEdgeOfClass(IsSimpleDeclOf.class, noSubClasses);
	}

	public IsSimpleDeclOf getFirstIsSimpleDeclOf(EdgeDirection orientation, boolean noSubClasses) {
		return (IsSimpleDeclOf)getFirstEdgeOfClass(IsSimpleDeclOf.class, orientation, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends IsBoundExprOf, ? extends Vertex>> getIsBoundExprOfIncidences() {
		return new IncidenceIterable<IsBoundExprOf, Vertex>(this, IsBoundExprOf.class);
	}
	
	public Iterable<EdgeVertexPair<? extends IsBoundExprOf, ? extends Vertex>> getIsBoundExprOfIncidences(boolean noSubClasses) {
		return new IncidenceIterable<IsBoundExprOf, Vertex>(this, IsBoundExprOf.class, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends IsBoundExprOf, ? extends Vertex>> getIsBoundExprOfIncidences(EdgeDirection direction, boolean noSubClasses) {
		return  new IncidenceIterable<IsBoundExprOf, Vertex>(this, IsBoundExprOf.class, direction, noSubClasses);
	}
	
	public Iterable<EdgeVertexPair<? extends IsBoundExprOf, ? extends Vertex>> getIsBoundExprOfIncidences(EdgeDirection direction) {
		return new IncidenceIterable<IsBoundExprOf, Vertex>(this, IsBoundExprOf.class, direction);
	}

	public Iterable<EdgeVertexPair<? extends Greql2Aggregation, ? extends Vertex>> getGreql2AggregationIncidences() {
		return new IncidenceIterable<Greql2Aggregation, Vertex>(this, Greql2Aggregation.class);
	}
	
	public Iterable<EdgeVertexPair<? extends Greql2Aggregation, ? extends Vertex>> getGreql2AggregationIncidences(boolean noSubClasses) {
		return new IncidenceIterable<Greql2Aggregation, Vertex>(this, Greql2Aggregation.class, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends Greql2Aggregation, ? extends Vertex>> getGreql2AggregationIncidences(EdgeDirection direction, boolean noSubClasses) {
		return  new IncidenceIterable<Greql2Aggregation, Vertex>(this, Greql2Aggregation.class, direction, noSubClasses);
	}
	
	public Iterable<EdgeVertexPair<? extends Greql2Aggregation, ? extends Vertex>> getGreql2AggregationIncidences(EdgeDirection direction) {
		return new IncidenceIterable<Greql2Aggregation, Vertex>(this, Greql2Aggregation.class, direction);
	}

	public Iterable<EdgeVertexPair<? extends IsTypeExprOf, ? extends Vertex>> getIsTypeExprOfIncidences() {
		return new IncidenceIterable<IsTypeExprOf, Vertex>(this, IsTypeExprOf.class);
	}
	
	public Iterable<EdgeVertexPair<? extends IsTypeExprOf, ? extends Vertex>> getIsTypeExprOfIncidences(boolean noSubClasses) {
		return new IncidenceIterable<IsTypeExprOf, Vertex>(this, IsTypeExprOf.class, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends IsTypeExprOf, ? extends Vertex>> getIsTypeExprOfIncidences(EdgeDirection direction, boolean noSubClasses) {
		return  new IncidenceIterable<IsTypeExprOf, Vertex>(this, IsTypeExprOf.class, direction, noSubClasses);
	}
	
	public Iterable<EdgeVertexPair<? extends IsTypeExprOf, ? extends Vertex>> getIsTypeExprOfIncidences(EdgeDirection direction) {
		return new IncidenceIterable<IsTypeExprOf, Vertex>(this, IsTypeExprOf.class, direction);
	}

	public Iterable<EdgeVertexPair<? extends IsTypeExprOfDeclaration, ? extends Vertex>> getIsTypeExprOfDeclarationIncidences() {
		return new IncidenceIterable<IsTypeExprOfDeclaration, Vertex>(this, IsTypeExprOfDeclaration.class);
	}
	
	public Iterable<EdgeVertexPair<? extends IsTypeExprOfDeclaration, ? extends Vertex>> getIsTypeExprOfDeclarationIncidences(boolean noSubClasses) {
		return new IncidenceIterable<IsTypeExprOfDeclaration, Vertex>(this, IsTypeExprOfDeclaration.class, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends IsTypeExprOfDeclaration, ? extends Vertex>> getIsTypeExprOfDeclarationIncidences(EdgeDirection direction, boolean noSubClasses) {
		return  new IncidenceIterable<IsTypeExprOfDeclaration, Vertex>(this, IsTypeExprOfDeclaration.class, direction, noSubClasses);
	}
	
	public Iterable<EdgeVertexPair<? extends IsTypeExprOfDeclaration, ? extends Vertex>> getIsTypeExprOfDeclarationIncidences(EdgeDirection direction) {
		return new IncidenceIterable<IsTypeExprOfDeclaration, Vertex>(this, IsTypeExprOfDeclaration.class, direction);
	}

	public Iterable<EdgeVertexPair<? extends IsDeclaredVarOf, ? extends Vertex>> getIsDeclaredVarOfIncidences() {
		return new IncidenceIterable<IsDeclaredVarOf, Vertex>(this, IsDeclaredVarOf.class);
	}
	
	public Iterable<EdgeVertexPair<? extends IsDeclaredVarOf, ? extends Vertex>> getIsDeclaredVarOfIncidences(boolean noSubClasses) {
		return new IncidenceIterable<IsDeclaredVarOf, Vertex>(this, IsDeclaredVarOf.class, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends IsDeclaredVarOf, ? extends Vertex>> getIsDeclaredVarOfIncidences(EdgeDirection direction, boolean noSubClasses) {
		return  new IncidenceIterable<IsDeclaredVarOf, Vertex>(this, IsDeclaredVarOf.class, direction, noSubClasses);
	}
	
	public Iterable<EdgeVertexPair<? extends IsDeclaredVarOf, ? extends Vertex>> getIsDeclaredVarOfIncidences(EdgeDirection direction) {
		return new IncidenceIterable<IsDeclaredVarOf, Vertex>(this, IsDeclaredVarOf.class, direction);
	}

	public Iterable<EdgeVertexPair<? extends IsSimpleDeclOf, ? extends Vertex>> getIsSimpleDeclOfIncidences() {
		return new IncidenceIterable<IsSimpleDeclOf, Vertex>(this, IsSimpleDeclOf.class);
	}
	
	public Iterable<EdgeVertexPair<? extends IsSimpleDeclOf, ? extends Vertex>> getIsSimpleDeclOfIncidences(boolean noSubClasses) {
		return new IncidenceIterable<IsSimpleDeclOf, Vertex>(this, IsSimpleDeclOf.class, noSubClasses);
	}

	public Iterable<EdgeVertexPair<? extends IsSimpleDeclOf, ? extends Vertex>> getIsSimpleDeclOfIncidences(EdgeDirection direction, boolean noSubClasses) {
		return  new IncidenceIterable<IsSimpleDeclOf, Vertex>(this, IsSimpleDeclOf.class, direction, noSubClasses);
	}
	
	public Iterable<EdgeVertexPair<? extends IsSimpleDeclOf, ? extends Vertex>> getIsSimpleDeclOfIncidences(EdgeDirection direction) {
		return new IncidenceIterable<IsSimpleDeclOf, Vertex>(this, IsSimpleDeclOf.class, direction);
	}

}
