/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;

import de.uni_koblenz.jgralab.greql2.schema.impl.IsArgumentOfImpl;
/**
FromVertexClass: Expression
FromRoleName : 
ToVertexClass: FunctionApplication
toRoleName : 
 */

public interface IsArgumentOf extends Aggregation, Greql2Aggregation {

	/**
	 * refers to the default implementation class of this interface
	 */
	public static final Class<IsArgumentOfImpl> IMPLEMENTATION_CLASS = IsArgumentOfImpl.class;

	/**
	 * @return the next Greql2Aggregation edge in the global edge sequence
	 */
	public Greql2Aggregation getNextGreql2AggregationInGraph();

	/**
	 * @return the next IsArgumentOf edge in the global edge sequence
	 */
	public IsArgumentOf getNextIsArgumentOfInGraph();

	/**
	 * @return the next IsArgumentOf edge in the global edge sequence
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsArgumentOf are accepted
	 */
	public IsArgumentOf getNextIsArgumentOfInGraph(boolean noSubClasses);

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 */
	public Greql2Aggregation getNextGreql2Aggregation();

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsArgumentOf at the "this" vertex
	 */
	public IsArgumentOf getNextIsArgumentOf();

	/**
	 * @return the next edge of class IsArgumentOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public IsArgumentOf getNextIsArgumentOf(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsArgumentOf at the "this" vertex
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsArgumentOf are accepted
	 */
	public IsArgumentOf getNextIsArgumentOf(boolean noSubClasses);

	/**
	 * @return the next edge of class IsArgumentOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsArgumentOf are accepted
	 */
	public IsArgumentOf getNextIsArgumentOf(EdgeDirection orientation, boolean noSubClasses);

}
