/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;

import de.uni_koblenz.jgralab.greql2.schema.impl.IsBoundVarOfImpl;
/**
FromVertexClass: Variable
FromRoleName : 
ToVertexClass: Greql2Expression
toRoleName : 
 */

public interface IsBoundVarOf extends Aggregation, Greql2Aggregation {

	/**
	 * refers to the default implementation class of this interface
	 */
	public static final Class<IsBoundVarOfImpl> IMPLEMENTATION_CLASS = IsBoundVarOfImpl.class;

	/**
	 * @return the next Greql2Aggregation edge in the global edge sequence
	 */
	public Greql2Aggregation getNextGreql2AggregationInGraph();

	/**
	 * @return the next IsBoundVarOf edge in the global edge sequence
	 */
	public IsBoundVarOf getNextIsBoundVarOfInGraph();

	/**
	 * @return the next IsBoundVarOf edge in the global edge sequence
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsBoundVarOf are accepted
	 */
	public IsBoundVarOf getNextIsBoundVarOfInGraph(boolean noSubClasses);

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 */
	public Greql2Aggregation getNextGreql2Aggregation();

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsBoundVarOf at the "this" vertex
	 */
	public IsBoundVarOf getNextIsBoundVarOf();

	/**
	 * @return the next edge of class IsBoundVarOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public IsBoundVarOf getNextIsBoundVarOf(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsBoundVarOf at the "this" vertex
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsBoundVarOf are accepted
	 */
	public IsBoundVarOf getNextIsBoundVarOf(boolean noSubClasses);

	/**
	 * @return the next edge of class IsBoundVarOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsBoundVarOf are accepted
	 */
	public IsBoundVarOf getNextIsBoundVarOf(EdgeDirection orientation, boolean noSubClasses);

}
