/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;

import de.uni_koblenz.jgralab.greql2.schema.impl.IsEdgeVertexListOfImpl;
/**
FromVertexClass: EdgeVertexList
FromRoleName : 
ToVertexClass: PathSystemConstruction
toRoleName : 
 */

public interface IsEdgeVertexListOf extends Aggregation, Greql2Aggregation {

	/**
	 * refers to the default implementation class of this interface
	 */
	public static final Class<IsEdgeVertexListOfImpl> IMPLEMENTATION_CLASS = IsEdgeVertexListOfImpl.class;

	/**
	 * @return the next Greql2Aggregation edge in the global edge sequence
	 */
	public Greql2Aggregation getNextGreql2AggregationInGraph();

	/**
	 * @return the next IsEdgeVertexListOf edge in the global edge sequence
	 */
	public IsEdgeVertexListOf getNextIsEdgeVertexListOfInGraph();

	/**
	 * @return the next IsEdgeVertexListOf edge in the global edge sequence
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsEdgeVertexListOf are accepted
	 */
	public IsEdgeVertexListOf getNextIsEdgeVertexListOfInGraph(boolean noSubClasses);

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 */
	public Greql2Aggregation getNextGreql2Aggregation();

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsEdgeVertexListOf at the "this" vertex
	 */
	public IsEdgeVertexListOf getNextIsEdgeVertexListOf();

	/**
	 * @return the next edge of class IsEdgeVertexListOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public IsEdgeVertexListOf getNextIsEdgeVertexListOf(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsEdgeVertexListOf at the "this" vertex
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsEdgeVertexListOf are accepted
	 */
	public IsEdgeVertexListOf getNextIsEdgeVertexListOf(boolean noSubClasses);

	/**
	 * @return the next edge of class IsEdgeVertexListOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsEdgeVertexListOf are accepted
	 */
	public IsEdgeVertexListOf getNextIsEdgeVertexListOf(EdgeDirection orientation, boolean noSubClasses);

}
