/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;

import de.uni_koblenz.jgralab.greql2.schema.impl.IsExprOfImpl;
/**
FromVertexClass: Expression
FromRoleName : 
ToVertexClass: Definition
toRoleName : 
 */

public interface IsExprOf extends Aggregation, Greql2Aggregation {

	/**
	 * refers to the default implementation class of this interface
	 */
	public static final Class<IsExprOfImpl> IMPLEMENTATION_CLASS = IsExprOfImpl.class;

	/**
	 * @return the next Greql2Aggregation edge in the global edge sequence
	 */
	public Greql2Aggregation getNextGreql2AggregationInGraph();

	/**
	 * @return the next IsExprOf edge in the global edge sequence
	 */
	public IsExprOf getNextIsExprOfInGraph();

	/**
	 * @return the next IsExprOf edge in the global edge sequence
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsExprOf are accepted
	 */
	public IsExprOf getNextIsExprOfInGraph(boolean noSubClasses);

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 */
	public Greql2Aggregation getNextGreql2Aggregation();

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsExprOf at the "this" vertex
	 */
	public IsExprOf getNextIsExprOf();

	/**
	 * @return the next edge of class IsExprOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public IsExprOf getNextIsExprOf(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsExprOf at the "this" vertex
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsExprOf are accepted
	 */
	public IsExprOf getNextIsExprOf(boolean noSubClasses);

	/**
	 * @return the next edge of class IsExprOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsExprOf are accepted
	 */
	public IsExprOf getNextIsExprOf(EdgeDirection orientation, boolean noSubClasses);

}
