/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;

import de.uni_koblenz.jgralab.greql2.schema.impl.IsExponentOfImpl;
/**
FromVertexClass: IntLiteral
FromRoleName : 
ToVertexClass: ExponentiatedPathDescription
toRoleName : 
 */

public interface IsExponentOf extends Aggregation, Greql2Aggregation {

	/**
	 * refers to the default implementation class of this interface
	 */
	public static final Class<IsExponentOfImpl> IMPLEMENTATION_CLASS = IsExponentOfImpl.class;

	/**
	 * @return the next Greql2Aggregation edge in the global edge sequence
	 */
	public Greql2Aggregation getNextGreql2AggregationInGraph();

	/**
	 * @return the next IsExponentOf edge in the global edge sequence
	 */
	public IsExponentOf getNextIsExponentOfInGraph();

	/**
	 * @return the next IsExponentOf edge in the global edge sequence
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsExponentOf are accepted
	 */
	public IsExponentOf getNextIsExponentOfInGraph(boolean noSubClasses);

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 */
	public Greql2Aggregation getNextGreql2Aggregation();

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsExponentOf at the "this" vertex
	 */
	public IsExponentOf getNextIsExponentOf();

	/**
	 * @return the next edge of class IsExponentOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public IsExponentOf getNextIsExponentOf(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsExponentOf at the "this" vertex
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsExponentOf are accepted
	 */
	public IsExponentOf getNextIsExponentOf(boolean noSubClasses);

	/**
	 * @return the next edge of class IsExponentOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsExponentOf are accepted
	 */
	public IsExponentOf getNextIsExponentOf(EdgeDirection orientation, boolean noSubClasses);

}
