/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;

import de.uni_koblenz.jgralab.greql2.schema.impl.IsGoalRestrOfImpl;
/**
FromVertexClass: Expression
FromRoleName : 
ToVertexClass: PathDescription
toRoleName : 
 */

public interface IsGoalRestrOf extends Aggregation, Greql2Aggregation {

	/**
	 * refers to the default implementation class of this interface
	 */
	public static final Class<IsGoalRestrOfImpl> IMPLEMENTATION_CLASS = IsGoalRestrOfImpl.class;

	/**
	 * @return the next Greql2Aggregation edge in the global edge sequence
	 */
	public Greql2Aggregation getNextGreql2AggregationInGraph();

	/**
	 * @return the next IsGoalRestrOf edge in the global edge sequence
	 */
	public IsGoalRestrOf getNextIsGoalRestrOfInGraph();

	/**
	 * @return the next IsGoalRestrOf edge in the global edge sequence
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsGoalRestrOf are accepted
	 */
	public IsGoalRestrOf getNextIsGoalRestrOfInGraph(boolean noSubClasses);

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 */
	public Greql2Aggregation getNextGreql2Aggregation();

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsGoalRestrOf at the "this" vertex
	 */
	public IsGoalRestrOf getNextIsGoalRestrOf();

	/**
	 * @return the next edge of class IsGoalRestrOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public IsGoalRestrOf getNextIsGoalRestrOf(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsGoalRestrOf at the "this" vertex
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsGoalRestrOf are accepted
	 */
	public IsGoalRestrOf getNextIsGoalRestrOf(boolean noSubClasses);

	/**
	 * @return the next edge of class IsGoalRestrOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsGoalRestrOf are accepted
	 */
	public IsGoalRestrOf getNextIsGoalRestrOf(EdgeDirection orientation, boolean noSubClasses);

}
