/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;

import de.uni_koblenz.jgralab.greql2.schema.impl.IsPartOfImpl;
/**
FromVertexClass: Expression
FromRoleName : 
ToVertexClass: ValueConstruction
toRoleName : 
 */

public interface IsPartOf extends Aggregation, Greql2Aggregation {

	/**
	 * refers to the default implementation class of this interface
	 */
	public static final Class<IsPartOfImpl> IMPLEMENTATION_CLASS = IsPartOfImpl.class;

	/**
	 * @return the next Greql2Aggregation edge in the global edge sequence
	 */
	public Greql2Aggregation getNextGreql2AggregationInGraph();

	/**
	 * @return the next IsPartOf edge in the global edge sequence
	 */
	public IsPartOf getNextIsPartOfInGraph();

	/**
	 * @return the next IsPartOf edge in the global edge sequence
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsPartOf are accepted
	 */
	public IsPartOf getNextIsPartOfInGraph(boolean noSubClasses);

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 */
	public Greql2Aggregation getNextGreql2Aggregation();

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsPartOf at the "this" vertex
	 */
	public IsPartOf getNextIsPartOf();

	/**
	 * @return the next edge of class IsPartOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public IsPartOf getNextIsPartOf(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsPartOf at the "this" vertex
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsPartOf are accepted
	 */
	public IsPartOf getNextIsPartOf(boolean noSubClasses);

	/**
	 * @return the next edge of class IsPartOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsPartOf are accepted
	 */
	public IsPartOf getNextIsPartOf(EdgeDirection orientation, boolean noSubClasses);

}
