/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;

import de.uni_koblenz.jgralab.greql2.schema.impl.IsQuantifierOfImpl;
/**
FromVertexClass: Quantifier
FromRoleName : 
ToVertexClass: QuantifiedExpression
toRoleName : 
 */

public interface IsQuantifierOf extends Aggregation, Greql2Aggregation {

	/**
	 * refers to the default implementation class of this interface
	 */
	public static final Class<IsQuantifierOfImpl> IMPLEMENTATION_CLASS = IsQuantifierOfImpl.class;

	/**
	 * @return the next Greql2Aggregation edge in the global edge sequence
	 */
	public Greql2Aggregation getNextGreql2AggregationInGraph();

	/**
	 * @return the next IsQuantifierOf edge in the global edge sequence
	 */
	public IsQuantifierOf getNextIsQuantifierOfInGraph();

	/**
	 * @return the next IsQuantifierOf edge in the global edge sequence
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsQuantifierOf are accepted
	 */
	public IsQuantifierOf getNextIsQuantifierOfInGraph(boolean noSubClasses);

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 */
	public Greql2Aggregation getNextGreql2Aggregation();

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsQuantifierOf at the "this" vertex
	 */
	public IsQuantifierOf getNextIsQuantifierOf();

	/**
	 * @return the next edge of class IsQuantifierOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public IsQuantifierOf getNextIsQuantifierOf(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsQuantifierOf at the "this" vertex
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsQuantifierOf are accepted
	 */
	public IsQuantifierOf getNextIsQuantifierOf(boolean noSubClasses);

	/**
	 * @return the next edge of class IsQuantifierOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsQuantifierOf are accepted
	 */
	public IsQuantifierOf getNextIsQuantifierOf(EdgeDirection orientation, boolean noSubClasses);

}
