/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;

import de.uni_koblenz.jgralab.greql2.schema.impl.IsRestrictedExprOfImpl;
/**
FromVertexClass: Expression
FromRoleName : 
ToVertexClass: RestrictedExpression
toRoleName : 
 */

public interface IsRestrictedExprOf extends Aggregation, Greql2Aggregation {

	/**
	 * refers to the default implementation class of this interface
	 */
	public static final Class<IsRestrictedExprOfImpl> IMPLEMENTATION_CLASS = IsRestrictedExprOfImpl.class;

	/**
	 * @return the next Greql2Aggregation edge in the global edge sequence
	 */
	public Greql2Aggregation getNextGreql2AggregationInGraph();

	/**
	 * @return the next IsRestrictedExprOf edge in the global edge sequence
	 */
	public IsRestrictedExprOf getNextIsRestrictedExprOfInGraph();

	/**
	 * @return the next IsRestrictedExprOf edge in the global edge sequence
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsRestrictedExprOf are accepted
	 */
	public IsRestrictedExprOf getNextIsRestrictedExprOfInGraph(boolean noSubClasses);

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 */
	public Greql2Aggregation getNextGreql2Aggregation();

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsRestrictedExprOf at the "this" vertex
	 */
	public IsRestrictedExprOf getNextIsRestrictedExprOf();

	/**
	 * @return the next edge of class IsRestrictedExprOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public IsRestrictedExprOf getNextIsRestrictedExprOf(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsRestrictedExprOf at the "this" vertex
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsRestrictedExprOf are accepted
	 */
	public IsRestrictedExprOf getNextIsRestrictedExprOf(boolean noSubClasses);

	/**
	 * @return the next edge of class IsRestrictedExprOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsRestrictedExprOf are accepted
	 */
	public IsRestrictedExprOf getNextIsRestrictedExprOf(EdgeDirection orientation, boolean noSubClasses);

}
