/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;

import de.uni_koblenz.jgralab.greql2.schema.impl.IsRestrictionOfImpl;
/**
FromVertexClass: Expression
FromRoleName : 
ToVertexClass: RestrictedExpression
toRoleName : 
 */

public interface IsRestrictionOf extends Aggregation, Greql2Aggregation {

	/**
	 * refers to the default implementation class of this interface
	 */
	public static final Class<IsRestrictionOfImpl> IMPLEMENTATION_CLASS = IsRestrictionOfImpl.class;

	/**
	 * @return the next Greql2Aggregation edge in the global edge sequence
	 */
	public Greql2Aggregation getNextGreql2AggregationInGraph();

	/**
	 * @return the next IsRestrictionOf edge in the global edge sequence
	 */
	public IsRestrictionOf getNextIsRestrictionOfInGraph();

	/**
	 * @return the next IsRestrictionOf edge in the global edge sequence
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsRestrictionOf are accepted
	 */
	public IsRestrictionOf getNextIsRestrictionOfInGraph(boolean noSubClasses);

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 */
	public Greql2Aggregation getNextGreql2Aggregation();

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsRestrictionOf at the "this" vertex
	 */
	public IsRestrictionOf getNextIsRestrictionOf();

	/**
	 * @return the next edge of class IsRestrictionOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public IsRestrictionOf getNextIsRestrictionOf(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsRestrictionOf at the "this" vertex
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsRestrictionOf are accepted
	 */
	public IsRestrictionOf getNextIsRestrictionOf(boolean noSubClasses);

	/**
	 * @return the next edge of class IsRestrictionOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsRestrictionOf are accepted
	 */
	public IsRestrictionOf getNextIsRestrictionOf(EdgeDirection orientation, boolean noSubClasses);

}
