/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;

import de.uni_koblenz.jgralab.greql2.schema.impl.IsRootOfImpl;
/**
FromVertexClass: Expression
FromRoleName : 
ToVertexClass: PathSystemConstruction
toRoleName : 
 */

public interface IsRootOf extends Aggregation, Greql2Aggregation {

	/**
	 * refers to the default implementation class of this interface
	 */
	public static final Class<IsRootOfImpl> IMPLEMENTATION_CLASS = IsRootOfImpl.class;

	/**
	 * @return the next Greql2Aggregation edge in the global edge sequence
	 */
	public Greql2Aggregation getNextGreql2AggregationInGraph();

	/**
	 * @return the next IsRootOf edge in the global edge sequence
	 */
	public IsRootOf getNextIsRootOfInGraph();

	/**
	 * @return the next IsRootOf edge in the global edge sequence
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsRootOf are accepted
	 */
	public IsRootOf getNextIsRootOfInGraph(boolean noSubClasses);

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 */
	public Greql2Aggregation getNextGreql2Aggregation();

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsRootOf at the "this" vertex
	 */
	public IsRootOf getNextIsRootOf();

	/**
	 * @return the next edge of class IsRootOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public IsRootOf getNextIsRootOf(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsRootOf at the "this" vertex
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsRootOf are accepted
	 */
	public IsRootOf getNextIsRootOf(boolean noSubClasses);

	/**
	 * @return the next edge of class IsRootOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsRootOf are accepted
	 */
	public IsRootOf getNextIsRootOf(EdgeDirection orientation, boolean noSubClasses);

}
