/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema;

import de.uni_koblenz.jgralab.Aggregation;
import de.uni_koblenz.jgralab.EdgeDirection;

import de.uni_koblenz.jgralab.greql2.schema.impl.IsStartExprOfImpl;
/**
FromVertexClass: Expression
FromRoleName : 
ToVertexClass: PathExpression
toRoleName : 
 */

public interface IsStartExprOf extends Aggregation, Greql2Aggregation {

	/**
	 * refers to the default implementation class of this interface
	 */
	public static final Class<IsStartExprOfImpl> IMPLEMENTATION_CLASS = IsStartExprOfImpl.class;

	/**
	 * @return the next Greql2Aggregation edge in the global edge sequence
	 */
	public Greql2Aggregation getNextGreql2AggregationInGraph();

	/**
	 * @return the next IsStartExprOf edge in the global edge sequence
	 */
	public IsStartExprOf getNextIsStartExprOfInGraph();

	/**
	 * @return the next IsStartExprOf edge in the global edge sequence
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsStartExprOf are accepted
	 */
	public IsStartExprOf getNextIsStartExprOfInGraph(boolean noSubClasses);

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 */
	public Greql2Aggregation getNextGreql2Aggregation();

	/**
	 * @return the next edge of class Greql2Aggregation at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public Greql2Aggregation getNextGreql2Aggregation(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsStartExprOf at the "this" vertex
	 */
	public IsStartExprOf getNextIsStartExprOf();

	/**
	 * @return the next edge of class IsStartExprOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public IsStartExprOf getNextIsStartExprOf(EdgeDirection orientation);

	/**
	 * @return the next edge of class IsStartExprOf at the "this" vertex
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsStartExprOf are accepted
	 */
	public IsStartExprOf getNextIsStartExprOf(boolean noSubClasses);

	/**
	 * @return the next edge of class IsStartExprOf at the "this" vertex
	 * @param orientation the orientation of the edge
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsStartExprOf are accepted
	 */
	public IsStartExprOf getNextIsStartExprOf(EdgeDirection orientation, boolean noSubClasses);

}
