/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.greql2.schema;

import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.EdgeVertexPair;
import de.uni_koblenz.jgralab.Vertex;

import de.uni_koblenz.jgralab.greql2.schema.impl.QuantifierImpl;

public interface Quantifier extends Greql2Vertex, Vertex {

	/**
	 * refers to the default implementation class of this interface
	 */
	public static final Class<QuantifierImpl> IMPLEMENTATION_CLASS = QuantifierImpl.class;

	public String getName();

	public void setName(String name);

	/**
	 * @return the next Greql2Vertex vertex in the global vertex sequence
	 */
	public Greql2Vertex getNextGreql2Vertex();

	/**
	 * @return the next Quantifier vertex in the global vertex sequence
	 */
	public Quantifier getNextQuantifier();

	/**
	 * @return the next Quantifier vertex in the global vertex sequence
	 * @param noSubClasses if set to <code>true</code>, no subclasses of Quantifier are accepted
	 */
	public Quantifier getNextQuantifier(boolean noSubClasses);

	/**
	 * @return the first edge of class IsBoundExprOf at this vertex
	 */
	public IsBoundExprOf getFirstIsBoundExprOf();

	/**
	 * @return the first edge of class IsBoundExprOf at this vertex
	 * @param orientation the orientation of the edge
	 */
	public IsBoundExprOf getFirstIsBoundExprOf(EdgeDirection orientation);

	/**
	 * @return the first edge of class Greql2Aggregation at this vertex
	 */
	public Greql2Aggregation getFirstGreql2Aggregation();

	/**
	 * @return the first edge of class Greql2Aggregation at this vertex
	 * @param orientation the orientation of the edge
	 */
	public Greql2Aggregation getFirstGreql2Aggregation(EdgeDirection orientation);

	/**
	 * @return the first edge of class IsTypeExprOf at this vertex
	 */
	public IsTypeExprOf getFirstIsTypeExprOf();

	/**
	 * @return the first edge of class IsTypeExprOf at this vertex
	 * @param orientation the orientation of the edge
	 */
	public IsTypeExprOf getFirstIsTypeExprOf(EdgeDirection orientation);

	/**
	 * @return the first edge of class IsQuantifierOf at this vertex
	 */
	public IsQuantifierOf getFirstIsQuantifierOf();

	/**
	 * @return the first edge of class IsQuantifierOf at this vertex
	 * @param orientation the orientation of the edge
	 */
	public IsQuantifierOf getFirstIsQuantifierOf(EdgeDirection orientation);

	/**
	 * @return the first edge of class IsQuantifierOf at this vertex
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsQuantifierOf are accepted
	 */
	public IsQuantifierOf getFirstIsQuantifierOf(boolean noSubClasses);

	/**
	 * @return the first edge of class IsQuantifierOf at this vertex
	 * @param orientation the orientation of the edge
	 * @param noSubClasses if set to <code>true</code>, no subclasses of IsQuantifierOf are accepted
	 */
	public IsQuantifierOf getFirstIsQuantifierOf(EdgeDirection orientation, boolean noSubClasses);

	/**
	 * Returns an iterable for all incidence edges of this vertex that are of type IsQuantifierOf or subtypes
	 */
	public Iterable<EdgeVertexPair<? extends IsQuantifierOf, ? extends Vertex>> getIsQuantifierOfIncidences();
	
	/**
	 * Returns an iterable for all incidence edges of this vertex that are of type IsQuantifierOf
	 * @param noSubClasses toggles wether subclasses of IsQuantifierOf should be excluded
	 */
	public Iterable<EdgeVertexPair<? extends IsQuantifierOf, ? extends Vertex>> getIsQuantifierOfIncidences(boolean noSubClasses);
	/**
	 * Returns an iterable for all incidence edges of this vertex that are of type IsQuantifierOf
	 * @param direction EdgeDirection.IN or EdgeDirection.OUT, only edges of this direction will be included in the iterable
	 * @param noSubClasses toggles wether subclasses of IsQuantifierOf should be excluded
	 */
	public Iterable<EdgeVertexPair<? extends IsQuantifierOf, ? extends Vertex>> getIsQuantifierOfIncidences(EdgeDirection direction, boolean noSubClasses);
	
	/**
	 * Returns an iterable for all incidence edges of this vertex that are of type IsQuantifierOf
	 * @param direction EdgeDirection.IN or EdgeDirection.OUT, only edges of this direction will be included in the iterable
	 */
	public Iterable<EdgeVertexPair<? extends IsQuantifierOf, ? extends Vertex>> getIsQuantifierOfIncidences(EdgeDirection direction);

}
